In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import neattext.functions as nfx

import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity,linear_kernel

In [3]:
df = pd.read_csv("udemydata.csv")
df.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance,429400,2017-01-18,20:58:58Z,2017,1,18
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance,209400,2017-03-09,16:34:20Z,2017,3,9
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance,97830,2016-12-19,19:26:30Z,2016,12,19
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance,232845,2017-05-30,20:07:24Z,2017,5,30
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance,255200,2016-12-13,14:57:18Z,2016,12,13

In [5]:
list(dir(nfx))

['BTC_ADDRESS_REGEX',
 'CURRENCY_REGEX',
 'CURRENCY_SYMB_REGEX',
 'Counter',
 'DATE_REGEX',
 'EMAIL_REGEX',
 'EMOJI_REGEX',
 'HASTAG_REGEX',
 'MASTERCard_REGEX',
 'MD5_SHA_REGEX',
 'MOST_COMMON_PUNCT_REGEX',
 'NUMBERS_REGEX',
 'PHONE_REGEX',
 'PoBOX_REGEX',
 'SPECIAL_CHARACTERS_REGEX',
 'STOPWORDS',
 'STOPWORDS_de',
 'STOPWORDS_en',
 'STOPWORDS_es',
 'STOPWORDS_fr',
 'STOPWORDS_ru',
 'STOPWORDS_yo',
 'STREET_ADDRESS_REGEX',
 'TextFrame',
 'URL_PATTERN',
 'USER_HANDLES_REGEX',
 'VISACard_REGEX',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__generate_text',
 '__loader__',
 '__name__',
 '__numbers_dict',
 '__package__',
 '__spec__',
 '_lex_richness_herdan',
 '_lex_richness_maas_ttr',
 'clean_text',
 'defaultdict',
 'digit2words',
 'extract_btc_address',
 'extract_currencies',
 'extract_currency_symbols',
 'extract_dates',
 'extract_emails',
 'extract_emojis',
 'extract_hashtags',
 'extract_html_tags',
 'extract_mastercard_addr',
 'extract_md5sha',
 'extract_numbers',
 'extract_pattern',
 'extract_phone_numbers',
 'extract_postoffice_box',
 'extract_shortwords',
 'extract_special_characters',
 'extract_stopwords',
 'extract_street_address',
 'extract_terms_in_bracket',
 'extract_urls',
 'extract_userhandles',
 'extract_visacard_addr',
 'fix_contractions',
 'generate_sentence',
 'hamming_distance',
 'inverse_df',
 'lexical_richness',
 'markov_chain',
 'math',
 'nlargest',
 'normalize',
 'num2words',
 'random',
 're',
 'read_txt',
 'remove_accents',
 'remove_bad_quotes',
 'remove_btc_address',
 'remove_currencies',
 'remove_currency_symbols',
 'remove_custom_pattern',
 'remove_custom_words',
 'remove_dates',
 'remove_emails',
 'remove_emojis',
 'remove_hashtags',
 'remove_html_tags',
 'remove_mastercard_addr',
 'remove_md5sha',
 'remove_multiple_spaces',
 'remove_non_ascii',
 'remove_numbers',
 'remove_phone_numbers',
 'remove_postoffice_box',
 'remove_puncts',
 'remove_punctuations',
 'remove_shortwords',
 'remove_special_characters',
 'remove_stopwords',
 'remove_street_address',
 'remove_terms_in_bracket',
 'remove_urls',
 'remove_userhandles',
 'remove_visacard_addr',
 'replace_bad_quotes',
 'replace_currencies',
 'replace_currency_symbols',
 'replace_dates',
 'replace_emails',
 'replace_emojis',
 'replace_numbers',
 'replace_phone_numbers',
 'replace_special_characters',
 'replace_term',
 'replace_urls',
 'string',
 'term_freq',
 'to_txt',
 'unicodedata',
 'word_freq',
 'word_length_freq']

In [10]:
list((df['course_title']))

['Ultimate Investment Banking Course',
 'Complete GST Course & Certification - Grow Your CA Practice',
 'Financial Modeling for Business Analysts and Consultants',
 'Beginner to Pro - Financial Analysis in Excel 2017',
 'How To Maximize Your Profits Trading Options',
 'Trading Penny Stocks: A Guide for All Levels In 2017',
 'Investing And Trading For Beginners: Mastering Price Charts',
 'Trading Stock Chart Patterns For Immediate, Explosive Gains',
 'Options Trading 3 : Advanced Stock Profit and Success Method',
 'The Only Investment Strategy You Need For Your Retirement',
 "Forex Trading Secrets of the Pros With Amazon's AWS",
 'Trading Options With Money Flow',
 'Financial Management Risk and Return For Securities',
 'Forex Trading Course: Work Smarter Not Harder Proven Results',
 'Python Algo Trading: Sentiment Trading with News',
 'Short Selling: Learn To Sell Stocks Before The Fall',
 'Basic Technical Analysis: Learn the structure of the market',
 'The Complete Chart Pattern Trading Course: A Proven Approach',
 '7 Deadly Mistakes of Investing that Will Slash Your Profits!',
 'Financial Statements Made Easy',
 'Winning Forex Trading with Live Forex Trading Examples',
 'Forex Traders - Create Your First Trading Robot. No Coding!',
 'Create A Business From Home Trading Stocks Today In 2017',
 'Introduction to Accounting : Mastering Financial Statements',
 'The Complete Ethereum Course: Get .01 Ether In Your Wallet',
 'Beginner to Pro in PowerPoint: Complete PowerPoint Training',
 'Investing 101: The Complete Online Investing Course',
 'Create Your Own Hedge Fund: Trade Stocks Like A Fund Manager',
 'Learn MQL5: Build an 8-Currency Hedging Robot (MetaTrader 5)',
 'Forex Trading: Your Complete Guide to Get Started Like a Pro',
 'Python Algo Stock Trading: Automate Your Trading!',
 'THE Forex Robot: Incredible ROI (Robot Included)',
 'The Complete Bitcoin Course: Get .001 Bitcoin In Your Wallet',
 'Mastering High Probability Iron Condor Options Trading',
 'The Complete Short Course on Ethereum',
 'Options Trading Stocks: Proven Toolbox For Financial Success',
 'Forex Trading A-Z™ - With LIVE Examples of Forex Trading',
 'Introduction to Finance, Accounting, Modeling and Valuation',
 'Beginner to Pro in Excel: Financial Modeling and Valuation',
 'The Complete Investment Banking Course 2017',
 'The Complete Financial Analyst Course 2017',
 'Python for Finance: Investment Fundamentals & Data Analytics',
 'Financial Modeling for Startups & Small Businesses',
 'Options Trading - How to Win with Weekly Options',
 'Black Algo Trading: Build Your Trading Robot',
 'Accounting & Financial Statement Analysis: Complete Training',
 'Cryptocurrency Trading: Complete Guide To Trading Altcoins',
 'Forex Robots: Expect To Earn 175% P.A. Forex Robot Included!',
 'Three Steps Trading - Live Trading - Real Account',
 'Option Trading for Rookies:  Understand Options Completely',
 'How I Learned Stock Trading (and How You Can Too)',
 'Learn to Trade for Profit: Find and Trade Winning Stocks',
 'Trading Inside Bars - Master 1 Easy Pattern To Be Successful',
 'Four Fundamentals of Financial Planning',
 'Options Trading - Calendar Spread Course for Every Trader',
 'Dividend Investing: Build Your Portfolio for a Better Future',
 'Learn Accounting. Understand Business.',
 'How to Consistently Win Trading Stocks in 30 Days or Less',
 "A Beginner's Guide to Quantopian Futures API",
 'How to Buy Cheap Options - Options Trading Pricing Model',
 'Excel Crash Course: Master Excel for Financial Analysis',
 'Comprehensive Guide to Financial Markets, Investing &Trading',
 'Stock Trading Ninja: Complete System For Trading Success',
 'Hedge and Mutual Fund Careers: The Complete Guide',
 'Algorithmic Trading In Forex: Create Your First Forex Robot!',
 'The Power Modeling Bootcamp: Advanced Excel in 10 Days',
 'Options Trading Basics (3-Course Bundle)',
 'How to Win 97% of Your Options Trades',
 'How I Make Consistent Returns Trading Options',
 'Forex Strategies: Kelly Criterion, Larry Williams and more!',
 'Elite Trend Trader: Learn To Trade Stocks, Options & Forex',
 'Options Trading Introduction: Day Trade Stock Options',
 'The Almost Perfect Options Trading Strategy System - Unique',
 'Forex Trading -  Learn to Trade Forex Like the Banks',
 'Learn to Trade for Profit:Trading with Japanese Candlesticks',
 'The Most Powerful Options Spread Trading Front Ratio Spread',
 'What Finance Job is for You? Explanation of 14 Finance Roles',
 'The Blueprint for Successful Stock Trading',
 'Trading for Beginners - Intermediate Level',
 'Start Trading Stocks Using Technical Analysis!',
 'Learn How to Set Up an Incubator Hedge Fund - Step-by-Step',
 'VPS for Forex Trading - Protect Your Forex Robots',
 'Introduction to Accounting: The Language of Business',
 'Basic Excel for Basic Bookkeeping and Accounting',
 'Using \'The Greeks To Understand Options"',
 'Trading Options For Consistent Returns: Calendar Spreads',
 'How to Create Your Personal Budget',
 'The Complete Value Investing Course: A Proven Approach',
 'FOREX Trading with Price Action',
 'Emini ES Futures - Advanced Non Directional Options Trading',
 'Forex Trading - Advanced Fundamental Analysis',
 'How To Invest With Tiny Capital In Stocks ?',
 'Learn How To Successfully Trade Stocks: In 5 Simple Steps',
 'Test your knowledge in Basics of Accounting',
 'Forex MetaTrader 4: Master MT4 Like A Pro Forex Trader',
 'Test your Knowledge in Cost Accounting',
 'Intermediate Options trading concepts for Stocks and Options',
 'Options Trading 101: The Basics',
 'Practical Accounts APP Overview',
 'Bitcoin Profits for Beginners',
 'Trend Traders Club: How To Find And Trade Fast Moving Trends',
 'Financial Statements Basics',
 'High performance Stock Trading using key Options techniques',
 'Introduction to Financial Statement Analysis',
 'Basics of Economics (College Level)',
 'Stock Market Investing for Beginners',
 'Accounting for Beginners : Learn Basics in under 1 Hour',
 'Straddle Options Trading - Profit in Any Market Direction',
 'Fundamentals of Forex Trading',
 'Binary Options: Trading Strategies, 90% Accuracy and Signals',
 'Website Investing 101 - Buying & Selling Online Businesses',
 'Practical Accounts & Bookkeeping Automated Overview ',
 'Live Account - ETF Trading System - Hacking The Stock Market',
 'Stock Market Leverage: How to Start Trading Options Wisely',
 'Stock Market Foundations',
 'Crash Course on Working Capital Management',
 'Advanced Accounting A Complete Study for CA / CMA / CFA / CS',
 '61% Profit In 1 Month - Crush Your Forex Trading Paradigm',
 'How to create a routine Trading',
 'Forex Trading Secrets |MT4 Robot (EA) inside, no coding',
 'Forex SOS Course: Trading Tweaks And Working Forex Strategy',
 'Introduction to Financial Modeling',
 'Quantitative Aptitude for Banking & Competitive Examinations',
 'Option Spreads and Credit Spreads Bundle',
 'B Com Accountancy I (Paper ECO 02 IGNOU)',
 'FOREX TRADING - Learn in a quick + profitable way + support',
 'Auditing Basics (Professional Course Level)',
 'Stock market Investing Encyclopedia: How to invest in stocks',
 'Learn the basics of preparing accounting statements',
 'Elliott Wave -Forex Trading With The Elliott Wave Theory',
 'Corporate Finance - A Brief Introduction',
 'Excel functions to analyze and visualize data',
 'Building Financial Statements in Excel',
 'Transfer Pricing A Complete Analysis',
 'Accounting: Get Hired Without Work Experience',
 'Forex Trading for Beginners - Basics',
 'Basic Bookkeeping Hacks',
 'Complete Trading Plan Course for Stocks & Forex (10 Hours)',
 'Forex Trading with Fixed \'Risk through Options Trading"',
 'Intro to Investment Banking, M&A, IPO, Modeling + Free Book',
 'How to Pick The Right Penny Stocks To Invest In 2017',
 'Top 10 Trading Ideas in the Equities Market',
 'Intro to Financial Modeling',
 'Shark Accounting - Building a Business by the Numbers!',
 'Forex Trading MAKE YOUR FIRST TRADE TODAY!',
 'Accounting in 60 Minutes - A Brief Introduction',
 'SAP FICO For Beginners - A Guide to SAP Financial Accounts',
 'Learn how to double your Forex Trading Account in one trade',
 'Accounting Superpowers: Learn Accounts, Understand Business!',
 'Python Algo Trading: FX Trading with Oanda',
 'Save on Your Taxes',
 'Financial Model Basics: Build a model from start to finish',
 'Option Trading for Rookies: The Covered Call Option Strategy',
 'EFT for Stock Options Trading Success & Making Better Trades',
 'Learn to Trade the Stock Market without Blowing Your Profits',
 'Get a Credit Repair Publication On Amazon and Live LIFE..',
 'Fundamentals of Accounting',
 'RSI, Options Trading & Technical Analysis (3 Course Bundle)',
 'Basics of Mutual Funds for CA / CMA / CS / CFA Exams',
 'Accounting 101: How to read an Accounting Balance Sheet',
 'Stock Options Day Trading Mindset for Success',
 'Introduction to bookkeeping and Accounting',
 'Learn to Trade The News',
 'Value Investing, Taught by Six Superinvestors',
 'Trading for everyone - The Independent Investor Course I',
 'Get Acquired: Learn From The Head Of Acquisitions For eBay',
 'Stock Market investment: Practical Accounting',
 'How to remove \'Risk from Penny Stocks - Options Trading"',
 'Accounting Basics in 66 Minutes (absolutely for beginners)',
 'Tax Accounting: Difficult Topic, Made Easy to Understand',
 'Analysis of Company Financial Statements',
 'Forex Trading Like Banks – Step by Step with Live Examples',
 'Fundamentals of Investing!',
 'Bank Financial Management A Comprehensive Study',
 'Learn to Trade Forex and Stocks: From Beginner to Advanced',
 'Master \'Technical Analysis and Chart reading skills Bundle"',
 'Naked Put Options Trade Covered Call & Poor Man Covered Call',
 'The Ultimate Guide to Dividend & Dividend Growth Investing',
 'Charting for Beginners 101: Technical Analysis Demystified',
 'Build a DCF Valuation Model',
 'Introductory Financial Accounting',
 'Introduction to Cryptocurrencies and Blockchain',
 'Trade Pullback Candlestick Strategy - Make Consistent Pips',
 'Accounting Standards Basics (Professional Course Level)',
 'Use the Magic Multiple Moving Average Forex Trading system',
 'QuickBooks 2015 Training for Newbies',
 'TRADING PSYCHOLOGY: Trading Mindset Mastery',
 'Option Trading: How to Adjust Delta-Neutral Strangles!',
 'Profitable binary option trading strategy',
 'Tax Strategy: Financial Planning for Beginners',
 'Accounting 2 Simplified for You',
 'Project Funding Modelling (for Professionals)',
 'Investing: How I Consistently Beat The Stock Market',
 'Bookkeeping Basics:  Understand the Fundamentals',
 'Leasing - A Comprehensive Study (Professional Course Level)',
 'Trading Options For Consistent Returns: Options Basics',
 'TechniTrader Leading Hybrid Indicator Trading',
 'Financial modeling: Build a DCF equity valuation model',
 'CryptoArbitrager: Bitcoin Trading Robot (no mining)',
 'Accounting Is Easy (for Beginners)',
 'Non Directional Weekly Options Trading System - ETF & Emini',
 'The Complete Position Trading Course: Position Trading Stock',
 'Master Iron Condors - Double the credit for half the risk',
 'Basics of investing in Mutual Funds',
 'A Value Investing Approach to the Stock Market',
 'Learn how to INVEST for huge profits or make it big trading!',
 'How to Fund your Million Dollar Idea: Equity, Debt, Unfund',
 'Mastering Candlestick Charting : High Probability Trading',
 'Binary Options Course - Level 2',
 'Stock Technical Analysis with R',
 'Get to know the VIX Index (aka \'The Fear Index)"',
 'Apply finance concepts for smart project management',
 'Introduction to Futures Trading and Live Trade Demonstration',
 'Crowdfunding to Win',
 'Comprehensive Forex Mastery Program',
 'Preparation of Consolidated Financial Statements (Basic)',
 "Succeed in Bonds Even if You Don't Know Where to Start",
 'Learn to Trade for Profit: Ten Most Profitable Trading Rules',
 "Succeed in Lotto Even if You Don't Know Where to Start!",
 'CFA Corporate Finance Level 2',
 'Pin Bars: The Most Powerful Forex Trading Signal',
 'Stock Options Trades Using Interactive Brokers',
 'Introduction to Options - Strategies For Consistent Profits',
 'Risk in Forex Transactions - for CA / CS / CFA exams',
 'Basics of Business Statistics (College Level)',
 'Trading Seasonal Price Patterns in Stocks, Futures, & Forex!',
 'Interpreting Financial Statements',
 'Introduction to Bookkeeping (Accounting)',
 'CREDIT SPREAD SURGERY - Bear Call and Bull Put Mastery ',
 'Investment Banking: How to Land a Job on Wall Street',
 'Learn To Invest In Index Funds and ETFs In 7 Easy Steps',
 'Financial modeling: Build a multiples valuation model',
 'Trade Recap I - A Real Look at Futures Options Markets',
 'Advanced Stock Options for Serious Equity Investors!',
 'Trading Binary Options for Fun and Profit',
 'CFA: Fast Track your career in Finance',
 'How to be a Profitable Forex Trader',
 'Excel Dashboard - Interactive Excel Dashboard and Charts',
 'Accounting 101: Learn Business Finance Forecasting in 60mins',
 'The Securities Trade Lifecycle',
 'Double your Forex Account using the MAGIC MA trading robot',
 'Technical Analysis 101: How to Profit During Market Crashes',
 'Advanced Accounting for Investment Banking',
 'Investing In Stocks With 10 Simple Rules',
 'Venture Capital. What is it and Why it Matters to You!',
 'Cash Flow Valuation: Develop Your Financial Literacy',
 'Direction-Independ Trading - Elite Forex Traders  Strategy',
 'How to Become a Financial Analyst from Scratch!',
 'First Steps to Trading the Forexmarkets : Technical Analysis',
 'Financial analysis: Compare performance of companies',
 'Forex for Beginners: Easy Forex Trading for Beginners',
 'Investment Crowdfunding 101 (a.k.a Equity Crowdfunding)',
 'Read financial statements like a pro',
 '10 Numbers Every Business Owner Should Know',
 'Learn How To Trade Gold In 2017',
 'IAS 18 - Revenue',
 'Forex Trading: The High ROI Forex Trading End of Day Course',
 'Fundraise the Simplified Way: A Crowdfunding Blueprint',
 'Fundamentals of Accounting for Business Owners',
 'Practical Financial Statement Analysis',
 'Forex Management - Detailed Study for CA / CS / CFA Exams',
 'Financial Statement Review 101:  How to Find Errors',
 'Professional Risk Manager (PRM) Certification: Level 1',
 'International Tax  - Tax Beyond boundaries',
 'The Complete Financial Statement Analysis Course',
 'Advanced Excel functions',
 'Penny Stocks Value & Chart Pattern Trading (2 Course Bundle)',
 'Candlestick Analysis For Professional Traders',
 'Build A Career In Forex Trading- Learn Fundamental Analysis',
 'Financial Modeling: Build a Complete DCF Valuation Model',
 'Hands-on Financial Modeling (With 6 Excel Templates)',
 'CAIIB Advanced Bank Management (Part I)',
 'Stock Market investment:Non financial fundamental analysis',
 'Learn How to Play CashFlow Game',
 'Basics of Business Finance',
 'Accounting Made Easy 2',
 'Bitcoin: el futuro del dinero, hoy',
 'Aprende a invertir practicando',
 'Trading con retrocesos de Fibonacci',
 'Mit Finanzwissen zu besserem Unternehmertum',
 'Como hacer empresa en 10 sesiones prácticas',
 'المحاسبة للإداريين و غير المحاسبين',
 '株式投資で本当のファンダメンタル分析ができるようになる',
 'Curso de Trading práctico basado en casos reales',
 'Curso Avanzado de Trading',
 'สอนเทรดไบนารี่ อ๊อฟชั่นอย่างง่าย',
 'MQL4 Tutorial Golden Goose',
 'Análise de Concessão de Crédito',
 'Technical Analysis Using Elliott Wave Theory',
 'The Basics Of Volume Analysis',
 'Crash Course on Cost of Capital and Capital Structuring',
 'Business Accounting Made Easy',
 'Build a DCF Model from Scratch',
 'Multiply your returns using \'Value Investing",https://www.udemy.com/multiply-your-returns-using-value-investing/,true,20,1942,19,63,All Levels,4.5 hours,2015-07-23T00:08:33Z\n874284,Weekly Forex Analysis by Baraq FX"',
 'Technical Analysis - A practical approach for trade entry',
 'Mastering Technical Analysis : Maximizing Trading Profits',
 'The Complete Guide to Professional Trading with Elliott Wave',
 'A Complete Guide to Becoming a Trader on the Forex Market',
 'Stock Market for Beginners - Complete Starter Toolkit',
 'Beginners Binary Options Course',
 'Technical Analysis 101: Secrets of Trading Revealed',
 "Forex: What's a Trend and When it is Strong and Reliable",
 'Volatility Trading Analysis with R',
 'How To Profit From Stock Market Volatility',
 'Awaken the Accountant in You | Master the Accounting Basics',
 'WE WILL PAY YOU TO TRADE WITH US',
 'Situational Trading: Proven Option Strategy for any Scenario',
 'Portfolio Management for CA / CS / CFA exams',
 'Algorithmic Trading in MATLAB: WFAToolbox App GUI (Finance)',
 'Finding an Unlimited Amount of Investors',
 'Bookkeeping Made Easy',
 'BITCOIN VISUALLY. Part I.',
 'Learn and Master the Basics of Finance',
 'FOREX : LearnTo Trade the Improved ( Advanced ) Patterns',
 'Mastering the Market : (Technical Analysis + Candlestick)',
 'Mastering Countertrend Trading : High Profit Trading Pattern',
 'Exam 1 Review - Managerial Accounting (U of H)',
 '* An Integrated Approach to the Fundamentals of Accounting',
 'Get to grips with the CFA calculator',
 'Financial Model Fundamentals-Learn the Essential Skills',
 'Forex: Economic News Trading',
 'Analyze Real Estate Investments | Financial Modeling',
 'Forex For Beginners - A Guide To Currency Trading',
 'Raise Your Credit Score to 800 Or More....',
 'Financial Management Budgeting Techniques',
 'Forex Killing Divergence - How to trade with precision',
 'Working Capital Management for CA / CFA / CPA Exams',
 'Risk Analysis - Capital Budgeting for CA / CS / CFA exams',
 'Corporate Finance 101: Financial Statement Analysis & Ratios',
 'Mastering Futures Options for Beginners - Your Top 5 Plays!',
 'Professional Options Trading, Simplified',
 'Advanced Options Concepts - Probability, Greeks, Simulation',
 'Accounting Basics - A Complete Study',
 'Case Studies in Macro Economics',
 'My Forex Strategy that win consistently over and over',
 'Understand Banks & Financial Markets ',
 'Stock Technical Analysis with Python',
 'How to Become an Accountant from scratch!',
 'How to invest in Gold',
 'Automate Your Finances',
 'MBA Accounting and Finance for Managers(Paper MS04 of IGNOU)',
 'Accounting Made Easy: A Quick Guide to Financial Accounting',
 'Futures/Commodity Training (Basics)',
 'Cost Accounting Marginal Costing Theory and Practice',
 'The Big Volatility Short: The Best Trade On Wall Street!',
 'Master Finance in Three Hours',
 'Learn Options on Futures for Hedging Options and Stocks',
 'Option selling trading as income source. Beginners friendly',
 'Introduction to Value Growth Investing',
 'Become A Forex Trader - Forex trading like a professional',
 'Hedge Fund Trading System',
 'Bulletproof Personal Finance: Expert Asset Allocation',
 'Financial Accounting: The Complete Introductory Crash Course',
 'Learn About Trading Options from a real wallstreet trader',
 'Forex Rate -Why it fluctuates -for CA / CMA / CS / CFA Exams',
 'How to Build a Massive Stock Portfolio from Zero!',
 'Introductory Forex Trading Course',
 'Budgeting Hacks to Build Wealth!',
 'Accounting and Finance for Bankers - A Comprehensive Study',
 'Forex Prep Academy for Beginners-Real trades!',
 'Accounting for Deferred Taxes (Professional Course Level)',
 'TRADING TRUTHS',
 'The Binary Institute - Introductory Course in Binary Options',
 'Forex Trading vs Option Trading',
 'How to Invest in Stocks + Billionaire Investing Tips',
 'Value Investing For Beginners',
 'TRADING TACTICS',
 'MQL4 Tutorial Bootcamp - Trading Robot Coding in Metatrader4',
 'Ultimate Retirement: Build Your Own Dynamic Retirement Plan',
 'build a solid foundation for trading options',
 'Forex Scam: Avoid the scam today',
 'Cost Accounting Crash Course',
 'Option Trading for Rookies: Basic Option Strategies',
 'Business Analysis:  Working with Use Cases',
 'Learn to Raise the Funds You Need via Crowdfunding',
 'Business finances',

In [12]:
df['cleantitle'] = df['course_title'].apply(nfx.remove_stopwords)
df['cleantitle'] = df['cleantitle'].apply(nfx.remove_special_characters)
list(df['cleantitle'])

['Ultimate Investment Banking Course',
 'Complete GST Course  Certification  Grow Practice',
 'Financial Modeling Business Analysts Consultants',
 'Beginner Pro  Financial Analysis Excel 2017',
 'Maximize Profits Trading Options',
 'Trading Penny Stocks Guide Levels 2017',
 'Investing Trading Beginners Mastering Price Charts',
 'Trading Stock Chart Patterns Immediate Explosive Gains',
 'Options Trading 3  Advanced Stock Profit Success Method',
 'Investment Strategy Need Retirement',
 'Forex Trading Secrets Pros Amazons AWS',
 'Trading Options Money Flow',
 'Financial Management Risk Return Securities',
 'Forex Trading Course Work Smarter Harder Proven Results',
 'Python Algo Trading Sentiment Trading News',
 'Short Selling Learn Sell Stocks Fall',
 'Basic Technical Analysis Learn structure market',
 'Complete Chart Pattern Trading Course Proven Approach',
 '7 Deadly Mistakes Investing Slash Profits',
 'Financial Statements Easy',
 'Winning Forex Trading Live Forex Trading Examples',
 'Forex Traders  Create Trading Robot Coding',
 'Create Business Home Trading Stocks Today 2017',
 'Introduction Accounting  Mastering Financial Statements',
 'Complete Ethereum Course 01 Ether Wallet',
 'Beginner Pro PowerPoint Complete PowerPoint Training',
 'Investing 101 Complete Online Investing Course',
 'Create Hedge Fund Trade Stocks Like Fund Manager',
 'Learn MQL5 Build 8Currency Hedging Robot MetaTrader 5',
 'Forex Trading Complete Guide Started Like Pro',
 'Python Algo Stock Trading Automate Trading',
 'Forex Robot Incredible ROI Robot Included',
 'Complete Bitcoin Course 001 Bitcoin Wallet',
 'Mastering High Probability Iron Condor Options Trading',
 'Complete Short Course Ethereum',
 'Options Trading Stocks Proven Toolbox Financial Success',
 'Forex Trading AZ  LIVE Examples Forex Trading',
 'Introduction Finance Accounting Modeling Valuation',
 'Beginner Pro Excel Financial Modeling Valuation',
 'Complete Investment Banking Course 2017',
 'Complete Financial Analyst Course 2017',
 'Python Finance Investment Fundamentals  Data Analytics',
 'Financial Modeling Startups  Small Businesses',
 'Options Trading  Win Weekly Options',
 'Black Algo Trading Build Trading Robot',
 'Accounting  Financial Statement Analysis Complete Training',
 'Cryptocurrency Trading Complete Guide Trading Altcoins',
 'Forex Robots Expect Earn 175 PA Forex Robot Included',
 'Steps Trading  Live Trading  Real Account',
 'Option Trading Rookies Understand Options Completely',
 'Learned Stock Trading and Too',
 'Learn Trade Profit Find Trade Winning Stocks',
 'Trading Inside Bars  Master 1 Easy Pattern Successful',
 'Fundamentals Financial Planning',
 'Options Trading  Calendar Spread Course Trader',
 'Dividend Investing Build Portfolio Better Future',
 'Learn Accounting Understand Business',
 'Consistently Win Trading Stocks 30 Days',
 'Beginners Guide Quantopian Futures API',
 'Buy Cheap Options  Options Trading Pricing Model',
 'Excel Crash Course Master Excel Financial Analysis',
 'Comprehensive Guide Financial Markets Investing Trading',
 'Stock Trading Ninja Complete System Trading Success',
 'Hedge Mutual Fund Careers Complete Guide',
 'Algorithmic Trading Forex Create Forex Robot',
 'Power Modeling Bootcamp Advanced Excel 10 Days',
 'Options Trading Basics 3Course Bundle',
 'Win 97 Options Trades',
 'Consistent Returns Trading Options',
 'Forex Strategies Kelly Criterion Larry Williams more',
 'Elite Trend Trader Learn Trade Stocks Options  Forex',
 'Options Trading Introduction Day Trade Stock Options',
 'Perfect Options Trading Strategy System  Unique',
 'Forex Trading  Learn Trade Forex Like Banks',
 'Learn Trade ProfitTrading Japanese Candlesticks',
 'Powerful Options Spread Trading Ratio Spread',
 'Finance Job You Explanation 14 Finance Roles',
 'Blueprint Successful Stock Trading',
 'Trading Beginners  Intermediate Level',
 'Start Trading Stocks Technical Analysis',
 'Learn Set Incubator Hedge Fund  StepbyStep',
 'VPS Forex Trading  Protect Forex Robots',
 'Introduction Accounting Language Business',
 'Basic Excel Basic Bookkeeping Accounting',
 'The Greeks Understand Options',
 'Trading Options Consistent Returns Calendar Spreads',
 'Create Personal Budget',
 'Complete Value Investing Course Proven Approach',
 'FOREX Trading Price Action',
 'Emini ES Futures  Advanced Non Directional Options Trading',
 'Forex Trading  Advanced Fundamental Analysis',
 'Invest Tiny Capital Stocks ',
 'Learn Successfully Trade Stocks 5 Simple Steps',
 'Test knowledge Basics Accounting',
 'Forex MetaTrader 4 Master MT4 Like Pro Forex Trader',
 'Test Knowledge Cost Accounting',
 'Intermediate Options trading concepts Stocks Options',
 'Options Trading 101 Basics',
 'Practical Accounts APP Overview',
 'Bitcoin Profits Beginners',
 'Trend Traders Club Find Trade Fast Moving Trends',
 'Financial Statements Basics',
 'High performance Stock Trading key Options techniques',
 'Introduction Financial Statement Analysis',
 'Basics Economics College Level',
 'Stock Market Investing Beginners',
 'Accounting Beginners  Learn Basics 1 Hour',
 'Straddle Options Trading  Profit Market Direction',
 'Fundamentals Forex Trading',
 'Binary Options Trading Strategies 90 Accuracy Signals',
 'Website Investing 101  Buying  Selling Online Businesses',
 'Practical Accounts  Bookkeeping Automated Overview',
 'Live Account  ETF Trading System  Hacking Stock Market',
 'Stock Market Leverage Start Trading Options Wisely',
 'Stock Market Foundations',
 'Crash Course Working Capital Management',
 'Advanced Accounting Complete Study  CMA  CFA  CS',
 '61 Profit 1 Month  Crush Forex Trading Paradigm',
 'create routine Trading',
 'Forex Trading Secrets MT4 Robot EA inside coding',
 'Forex SOS Course Trading Tweaks Working Forex Strategy',
 'Introduction Financial Modeling',
 'Quantitative Aptitude Banking  Competitive Examinations',
 'Option Spreads Credit Spreads Bundle',
 'B Com Accountancy Paper ECO 02 IGNOU',
 'FOREX TRADING  Learn quick  profitable way  support',
 'Auditing Basics Professional Course Level',
 'Stock market Investing Encyclopedia invest stocks',
 'Learn basics preparing accounting statements',
 'Elliott Wave Forex Trading Elliott Wave Theory',
 'Corporate Finance  Brief Introduction',
 'Excel functions analyze visualize data',
 'Building Financial Statements Excel',
 'Transfer Pricing Complete Analysis',
 'Accounting Hired Work Experience',
 'Forex Trading Beginners  Basics',
 'Basic Bookkeeping Hacks',
 'Complete Trading Plan Course Stocks  Forex 10 Hours',
 'Forex Trading Fixed Risk Options Trading',
 'Intro Investment Banking MA IPO Modeling  Free Book',
 'Pick Right Penny Stocks Invest 2017',
 '10 Trading Ideas Equities Market',
 'Intro Financial Modeling',
 'Shark Accounting  Building Business Numbers',
 'Forex Trading TRADE TODAY',
 'Accounting 60 Minutes  Brief Introduction',
 'SAP FICO Beginners  Guide SAP Financial Accounts',
 'Learn double Forex Trading Account trade',
 'Accounting Superpowers Learn Accounts Understand Business',
 'Python Algo Trading FX Trading Oanda',
 'Save Taxes',
 'Financial Model Basics Build model start finish',
 'Option Trading Rookies Covered Option Strategy',
 'EFT Stock Options Trading Success  Making Better Trades',
 'Learn Trade Stock Market Blowing Profits',
 'Credit Repair Publication Amazon Live LIFE',
 'Fundamentals Accounting',
 'RSI Options Trading  Technical Analysis 3 Course Bundle',
 'Basics Mutual Funds  CMA  CS  CFA Exams',
 'Accounting 101 read Accounting Balance Sheet',
 'Stock Options Day Trading Mindset Success',
 'Introduction bookkeeping Accounting',
 'Learn Trade News',
 'Value Investing Taught Superinvestors',
 'Trading  Independent Investor Course',
 'Acquired Learn Head Acquisitions eBay',
 'Stock Market investment Practical Accounting',
 'remove Risk Penny Stocks  Options Trading',
 'Accounting Basics 66 Minutes absolutely beginners',
 'Tax Accounting Difficult Topic Easy Understand',
 'Analysis Company Financial Statements',
 'Forex Trading Like Banks  Step Step Live Examples',
 'Fundamentals Investing',
 'Bank Financial Management Comprehensive Study',
 'Learn Trade Forex Stocks Beginner Advanced',
 'Master Technical Analysis Chart reading skills Bundle',
 'Naked Options Trade Covered  Poor Man Covered',
 'Ultimate Guide Dividend  Dividend Growth Investing',
 'Charting Beginners 101 Technical Analysis Demystified',
 'Build DCF Valuation Model',
 'Introductory Financial Accounting',
 'Introduction Cryptocurrencies Blockchain',
 'Trade Pullback Candlestick Strategy  Consistent Pips',
 'Accounting Standards Basics Professional Course Level',
 'Use Magic Multiple Moving Average Forex Trading system',
 'QuickBooks 2015 Training Newbies',
 'TRADING PSYCHOLOGY Trading Mindset Mastery',
 'Option Trading Adjust DeltaNeutral Strangles',
 'Profitable binary option trading strategy',
 'Tax Strategy Financial Planning Beginners',
 'Accounting 2 Simplified',
 'Project Funding Modelling for Professionals',
 'Investing Consistently Beat Stock Market',
 'Bookkeeping Basics Understand Fundamentals',
 'Leasing  Comprehensive Study Professional Course Level',
 'Trading Options Consistent Returns Options Basics',
 'TechniTrader Leading Hybrid Indicator Trading',
 'Financial modeling Build DCF equity valuation model',
 'CryptoArbitrager Bitcoin Trading Robot no mining',
 'Accounting Easy for Beginners',
 'Non Directional Weekly Options Trading System  ETF  Emini',
 'Complete Position Trading Course Position Trading Stock',
 'Master Iron Condors  Double credit half risk',
 'Basics investing Mutual Funds',
 'Value Investing Approach Stock Market',
 'Learn INVEST huge profits big trading',
 'Fund Million Dollar Idea Equity Debt Unfund',
 'Mastering Candlestick Charting  High Probability Trading',
 'Binary Options Course  Level 2',
 'Stock Technical Analysis R',
 'know VIX Index aka The Fear Index',
 'Apply finance concepts smart project management',
 'Introduction Futures Trading Live Trade Demonstration',
 'Crowdfunding Win',
 'Comprehensive Forex Mastery Program',
 'Preparation Consolidated Financial Statements Basic',
 'Succeed Bonds Know Start',
 'Learn Trade Profit Profitable Trading Rules',
 'Succeed Lotto Know Start',
 'CFA Corporate Finance Level 2',
 'Pin Bars Powerful Forex Trading Signal',
 'Stock Options Trades Interactive Brokers',
 'Introduction Options  Strategies Consistent Profits',
 'Risk Forex Transactions   CS  CFA exams',
 'Basics Business Statistics College Level',
 'Trading Seasonal Price Patterns Stocks Futures  Forex',
 'Interpreting Financial Statements',
 'Introduction Bookkeeping Accounting',
 'CREDIT SPREAD SURGERY  Bear Bull Mastery',
 'Investment Banking Land Job Wall Street',
 'Learn Invest Index Funds ETFs 7 Easy Steps',
 'Financial modeling Build multiples valuation model',
 'Trade Recap  Real Look Futures Options Markets',
 'Advanced Stock Options Equity Investors',
 'Trading Binary Options Fun Profit',
 'CFA Fast Track career Finance',
 'Profitable Forex Trader',
 'Excel Dashboard  Interactive Excel Dashboard Charts',
 'Accounting 101 Learn Business Finance Forecasting 60mins',
 'Securities Trade Lifecycle',
 'Double Forex Account MAGIC trading robot',
 'Technical Analysis 101 Profit Market Crashes',
 'Advanced Accounting Investment Banking',
 'Investing Stocks 10 Simple Rules',
 'Venture Capital Matters You',
 'Cash Flow Valuation Develop Financial Literacy',
 'DirectionIndepend Trading  Elite Forex Traders Strategy',
 'Financial Analyst Scratch',
 'Steps Trading Forexmarkets  Technical Analysis',
 'Financial analysis Compare performance companies',
 'Forex Beginners Easy Forex Trading Beginners',
 'Investment Crowdfunding 101 aka Equity Crowdfunding',
 'Read financial statements like pro',
 '10 Numbers Business Owner Know',
 'Learn Trade Gold 2017',
 'IAS 18  Revenue',
 'Forex Trading High ROI Forex Trading End Day Course',
 'Fundraise Simplified Way Crowdfunding Blueprint',
 'Fundamentals Accounting Business Owners',
 'Practical Financial Statement Analysis',
 'Forex Management  Detailed Study  CS  CFA Exams',
 'Financial Statement Review 101 Find Errors',
 'Professional Risk Manager PRM Certification Level 1',
 'International Tax  Tax boundaries',
 'Complete Financial Statement Analysis Course',
 'Advanced Excel functions',
 'Penny Stocks Value  Chart Pattern Trading 2 Course Bundle',
 'Candlestick Analysis Professional Traders',
 'Build Career Forex Trading Learn Fundamental Analysis',
 'Financial Modeling Build Complete DCF Valuation Model',
 'Handson Financial Modeling With 6 Excel Templates',
 'CAIIB Advanced Bank Management Part I',
 'Stock Market investmentNon financial fundamental analysis',
 'Learn Play CashFlow Game',
 'Basics Business Finance',
 'Accounting Easy 2',
 'Bitcoin el futuro del dinero hoy',
 'Aprende invertir practicando',
 'Trading con retrocesos de Fibonacci',
 'Mit Finanzwissen zu besserem Unternehmertum',
 'Como hacer empresa en 10 sesiones prcticas',
 '    ',
 '',
 'Curso de Trading prctico basado en casos reales',
 'Curso Avanzado de Trading',
 ' ',
 'MQL4 Tutorial Golden Goose',
 'Anlise de Concesso de Crdito',
 'Technical Analysis Elliott Wave Theory',
 'Basics Volume Analysis',
 'Crash Course Cost Capital Capital Structuring',
 'Business Accounting Easy',
 'Build DCF Model Scratch',
 'Multiply returns Value Investinghttpswwwudemycommultiplyyourreturnsusingvalueinvestingtrue2019421963All Levels45 hours20150723T000833Z 874284Weekly Forex Analysis Baraq FX',
 'Technical Analysis  practical approach trade entry',
 'Mastering Technical Analysis  Maximizing Trading Profits',
 'Complete Guide Professional Trading Elliott Wave',
 'Complete Guide Trader Forex Market',
 'Stock Market Beginners  Complete Starter Toolkit',
 'Beginners Binary Options Course',
 'Technical Analysis 101 Secrets Trading Revealed',
 'Forex Whats Trend Strong Reliable',
 'Volatility Trading Analysis R',
 'Profit Stock Market Volatility',
 'Awaken Accountant  Master Accounting Basics',
 'PAY TRADE',
 'Situational Trading Proven Option Strategy Scenario',
 'Portfolio Management  CS  CFA exams',
 'Algorithmic Trading MATLAB WFAToolbox App GUI Finance',
 'Finding Unlimited Investors',
 'Bookkeeping Easy',
 'BITCOIN VISUALLY I',
 'Learn Master Basics Finance',
 'FOREX  LearnTo Trade Improved  Advanced  Patterns',
 'Mastering Market  Technical Analysis  Candlestick',
 'Mastering Countertrend Trading  High Profit Trading Pattern',
 'Exam 1 Review  Managerial Accounting U H',
 ' Integrated Approach Fundamentals Accounting',
 'grips CFA calculator',
 'Financial Model FundamentalsLearn Essential Skills',
 'Forex Economic News Trading',
 'Analyze Real Estate Investments  Financial Modeling',
 'Forex Beginners  Guide Currency Trading',
 'Raise Credit Score 800 More',
 'Financial Management Budgeting Techniques',
 'Forex Killing Divergence  trade precision',
 'Working Capital Management  CFA  CPA Exams',
 'Risk Analysis  Capital Budgeting  CS  CFA exams',
 'Corporate Finance 101 Financial Statement Analysis  Ratios',
 'Mastering Futures Options Beginners  5 Plays',
 'Professional Options Trading Simplified',
 'Advanced Options Concepts  Probability Greeks Simulation',
 'Accounting Basics  Complete Study',
 'Case Studies Macro Economics',
 'Forex Strategy win consistently',
 'Understand Banks  Financial Markets',
 'Stock Technical Analysis Python',
 'Accountant scratch',
 'invest Gold',
 'Automate Finances',
 'MBA Accounting Finance ManagersPaper MS04 IGNOU',
 'Accounting Easy Quick Guide Financial Accounting',
 'FuturesCommodity Training Basics',
 'Cost Accounting Marginal Costing Theory Practice',
 'Big Volatility Short Best Trade Wall Street',
 'Master Finance Hours',
 'Learn Options Futures Hedging Options Stocks',
 'Option selling trading income source Beginners friendly',
 'Introduction Value Growth Investing',
 'Forex Trader  Forex trading like professional',
 'Hedge Fund Trading System',
 'Bulletproof Personal Finance Expert Asset Allocation',
 'Financial Accounting Complete Introductory Crash Course',
 'Learn Trading Options real wallstreet trader',
 'Forex Rate Why fluctuates for  CMA  CS  CFA Exams',
 'Build Massive Stock Portfolio Zero',
 'Introductory Forex Trading Course',
 'Budgeting Hacks Build Wealth',
 'Accounting Finance Bankers  Comprehensive Study',
 'Forex Prep Academy BeginnersReal trades',
 'Accounting Deferred Taxes Professional Course Level',
 'TRADING TRUTHS',
 'Binary Institute  Introductory Course Binary Options',
 'Forex Trading vs Option Trading',
 'Invest Stocks  Billionaire Investing Tips',
 'Value Investing Beginners',
 'TRADING TACTICS',
 'MQL4 Tutorial Bootcamp  Trading Robot Coding Metatrader4',
 'Ultimate Retirement Build Dynamic Retirement Plan',
 'build solid foundation trading options',
 'Forex Scam Avoid scam today',
 'Cost Accounting Crash Course',
 'Option Trading Rookies Basic Option Strategies',
 'Business Analysis Working Use Cases',
 'Learn Raise Funds Need Crowdfunding',
 'Business finances',
 'Financial Accounting  Brief Introduction',
 'Trading Economic Indicators  Complete Trading System',
 'Foundation Options Trading Investing',
 'Option Trading  Earn Cant Predict Market',
 'Financial Analyst Skills Training FAST course 2017',
 'Covered Calls  Powerful Income Strategy Stock Traders',
 'Accounting 1 Simplified',
 'Value Investing White People Money',
 'Start Investing Simple Easy',
 'Basics Commerce Complete Study',
 'Passive Investing Blueprint  Build Wealth Passively',
 '7 Steps Introduction Trading',
 'Forex  Elliott Wave Theory Fibonacci',
 'Actuarial Profession Basic Sciences Principles',
 'Investing stocks Avoid stock market loss',
 'QuickBooks Online Complete Guide  Certification tips',
 'Build Financial Models  Value Companies Easy Way',
 'Adventure Capital pay debt',
 'Chart Patterns Trading Demystified',
 'Financial Planning  Analysis Building Companys Budget',
 'Simple things know start FOREX OFFER',
 'Practical Finance',
 'Forex Trading Comprehensive  Concise Forex Trading Course',
 'Leaps Options Trading System  Diagonal Leaps Options Spread',
 'Finance  Ratios Analysis  Interpretations',
 'Forex Trading  Learn Trade Scratch',
 'Technical Analysis tools Stocks Options trading',
 'Quantitative Trading Analysis R',
 'Penny Stocks King 2 Trade Penny Stocks 6 Hours',
 'Started Penny Stocks Step Step Guide Trading',
 'CPA 101 Master Affiliate Marketing Time',
 'Corporate Internal Controls Fraud Controls',
 'Forex trading tactics work',
 'Professional Risk Manager PRM Certification Level 2',
 'Trading Options Basics',
 'Practical Trading Financial Futures  Options Markets',
 'Bookkeeping simple',
 'Visual Learning Basic Accounting Course',
 'ChalkTalk Financial Accounting',
 '7 fundamentals Successful Cashflow Management',
 'trade options',
 'Coaching CourseInvestment Analysis clients',
 'Harnessing Power Growth Stocks',
 'Investment Banking Recruitment Series',
 'Business Banking 101',
 'CFA Level Workshop 2 Financial Reporting  Analysis',
 'Breakout Patterns Workshop Pattern Trader',
 'Asset Protection Offshore Companies',
 'Credit EIN Thats Linked SSN',
 'Financial Translation',
 'Pick Stocks',
 'Binary Beginners Mastery Strategy',
 'Accounting 101Master Class Understanding Business',
 'HighFrequency Trading  Dark Pools',
 'Crowdfund',
 'Financial Statement Fundamentals Small Biz  Investors',
 'Master Stock Market practice',
 'Introduction Trade Theory Technical Analysis Stocks',
 'Forex Trading Beginners Technical Trading',
 'IAS 12  Accounting Income Taxes Basics',
 'Surpassing Kickstarter Goals',
 'Simple Linear Regression Analysis  Complete Course ',
 'Forex Learn Trade Forex FX Consistently',
 'Trading HighROI Trading',
 'Fundraising 101',
 'Professional Bookkeeping  Accounting 2  Bank Daybook',
 'Filing Companies House UK',
 'Build Grow Protect Assets StepbyStep Guide',
 'Advantages ETF Options Index Options Trading',
 'Learn Trade Forex  Beginner Professional',
 'Investing Stocks Big Gains Fundamental Investing',

In [13]:
# count vectorizer is a tool used in NLP to convert a collection of text documents into a matrix of token (word) counts. it is 
#commonly used when preparig text data for ML models
#in simple , it turns words into numbers which is what models need to work with
countvectorizer = CountVectorizer()
CV = countvectorizer.fit_transform(df['cleantitle'])
CV

<3683x3564 sparse matrix of type '<class 'numpy.int64'>'
	with 18364 stored elements in Compressed Sparse Row format>

In [15]:
df_cv_words = pd.DataFrame(CV.todense(), columns=countvectorizer.get_feature_names())
df_cv_words

C:\python 3.10.6\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,000005,001,01,02,10,100,101,101master,102,10k,...,zend,zero,zerotohero,zf2,zinsen,zoho,zombie,zu,zuhause,zur
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3678,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3679,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3680,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3681,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3682,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
# cosine similarity measures how similar 2 vectors are - based on the angle between them - not their magnitude
# in NLp, it's commonly used to compare text documents after converting them into vectors(eg using countvectorizer or TFIDF vectorizer)
cosine_similarity = cosine_similarity(CV)
cosine_similarity

array([[1.        , 0.20412415, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.20412415, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.23570226],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.23570226, 0.        ,
        1.        ]])

In [18]:
courseindex = pd.Series(df.index,index = df['course_title'])
courseindex.drop_duplicates()
courseindex

course_title
Ultimate Investment Banking Course                                0
Complete GST Course & Certification - Grow Your CA Practice       1
Financial Modeling for Business Analysts and Consultants          2
Beginner to Pro - Financial Analysis in Excel 2017                3
How To Maximize Your Profits Trading Options                      4
                                                               ...
Learn jQuery from Scratch - Master of JavaScript library       3678
How To Design A WordPress Website With No Coding At All        3679
Learn and Build using Polymer                                  3680
CSS Animations: Create Amazing Effects on Your Website         3681
Using MODX CMS to Build Websites: A Beginner's Guide           3682
Length: 3683, dtype: int64

In [20]:
temp = df[df['course_title'].str.contains('Trading')]
temp.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day,cleantitle
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance,255200,2016-12-13,14:57:18Z,2016,12,13,Maximize Profits Trading Options
5,192870,Trading Penny Stocks: A Guide for All Levels I...,https://www.udemy.com/trading-penny-stocks-a-g...,True,150,9221,138,25,All Levels,3 hours,2014-05-02T15:13:30Z,Business Finance,1383150,2014-05-02,15:13:30Z,2014,5,2,Trading Penny Stocks Guide Levels 2017
6,739964,Investing And Trading For Beginners: Mastering...,https://www.udemy.com/investing-and-trading-fo...,True,65,1540,178,26,Beginner Level,1 hour,2016-02-21T18:23:12Z,Business Finance,100100,2016-02-21,18:23:12Z,2016,2,21,Investing Trading Beginners Mastering Price Ch...
7,403100,"Trading Stock Chart Patterns For Immediate, Ex...",https://www.udemy.com/trading-chart-patterns-f...,True,95,2917,148,23,All Levels,2.5 hours,2015-01-30T22:13:03Z,Business Finance,277115,2015-01-30,22:13:03Z,2015,1,30,Trading Stock Chart Patterns Immediate Explosi...
8,476268,Options Trading 3 : Advanced Stock Profit and ...,https://www.udemy.com/day-trading-stock-option...,True,195,5172,34,38,Expert Level,2.5 hours,2015-05-28T00:14:03Z,Business Finance,1008540,2015-05-28,00:14:03Z,2015,5,28,Options Trading 3 Advanced Stock Profit Succe...

In [21]:
top10 = temp.sort_values(by = 'num_subscribers', ascending=False).head(10)
top10

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day,cleantitle
44,301442,Black Algo Trading: Build Your Trading Robot,https://www.udemy.com/build-your-trading-robot/,True,200,20195,1113,227,All Levels,16 hours,2014-10-27T22:01:36Z,Business Finance,4039000,2014-10-27,22:01:36Z,2014,10,27,Black Algo Trading Build Trading Robot
108,265960,Fundamentals of Forex Trading,https://www.udemy.com/fundamentals-of-forex-tr...,False,0,17160,620,23,All Levels,1 hour,2014-08-29T20:10:38Z,Business Finance,0,2014-08-29,20:10:38Z,2014,8,29,Fundamentals Forex Trading
36,308690,Forex Trading A-Z™ - With LIVE Examples of For...,https://www.udemy.com/forex-trading/,True,195,16900,2476,52,Beginner Level,5.5 hours,2014-12-12T23:58:39Z,Business Finance,3295500,2014-12-12,23:58:39Z,2014,12,12,Forex Trading AZ LIVE Examples Forex Trading
74,285638,Learn to Trade for Profit:Trading with Japanes...,https://www.udemy.com/introduction-to-japanese...,True,60,16385,273,45,Beginner Level,3 hours,2014-09-02T03:53:13Z,Business Finance,983100,2014-09-02,03:53:13Z,2014,9,2,Learn Trade ProfitTrading Japanese Candlesticks
71,401784,Options Trading Introduction: Day Trade Stock ...,https://www.udemy.com/how-to-trade-stock-optio...,True,95,12394,218,30,Beginner Level,2.5 hours,2015-02-20T21:39:41Z,Business Finance,1177430,2015-02-20,21:39:41Z,2015,2,20,Options Trading Introduction Day Trade Stock O...
22,506568,Create A Business From Home Trading Stocks Tod...,https://www.udemy.com/work-from-home-buying-pe...,True,75,10149,83,16,All Levels,2 hours,2015-05-26T17:25:46Z,Business Finance,761175,2015-05-26,17:25:46Z,2015,5,26,Create Business Home Trading Stocks Today 2017
66,43319,Options Trading Basics (3-Course Bundle),https://www.udemy.com/learn-options-trading-co...,True,180,10100,985,45,Beginner Level,11 hours,2013-02-25T11:36:06Z,Business Finance,1818000,2013-02-25,11:36:06Z,2013,2,25,Options Trading Basics 3Course Bundle
833,706942,Forex Trading For Beginners,https://www.udemy.com/forex-trading-for-beginn...,False,0,9483,183,22,Beginner Level,2 hours,2016-01-14T02:46:59Z,Business Finance,0,2016-01-14,02:46:59Z,2016,1,14,Forex Trading Beginners
62,165964,Stock Trading Ninja: Complete System For Tradi...,https://www.udemy.com/stock-trading-ninja-lear...,True,155,9445,497,38,All Levels,4.5 hours,2014-02-19T19:04:28Z,Business Finance,1463975,2014-02-19,19:04:28Z,2014,2,19,Stock Trading Ninja Complete System Trading Su...
5,192870,Trading Penny Stocks: A Guide for All Levels I...,https://www.udemy.com/trading-penny-stocks-a-g...,True,150,9221,138,25,All Levels,3 hours,2014-05-02T15:13:30Z,Business Finance,1383150,2014-05-02,15:13:30Z,2014,5,2,Trading Penny Stocks Guide Levels 2017

In [28]:
index = courseindex['How To Maximize Your Profits Trading Options']

In [29]:
scores = list(enumerate(cosine_similarity[index]))
scores

[(0, 0.0),
 (1, 0.0),
 (2, 0.0),
 (3, 0.0),
 (4, 1.0),
 (5, 0.20412414523193154),
 (6, 0.20412414523193154),
 (7, 0.1889822365046136),
 (8, 0.3779644730092272),
 (9, 0.0),
 (10, 0.20412414523193154),
 (11, 0.5),
 (12, 0.0),
 (13, 0.17677669529663687),
 (14, 0.35355339059327373),
 (15, 0.0),
 (16, 0.0),
 (17, 0.1889822365046136),
 (18, 0.22360679774997896),
 (19, 0.0),
 (20, 0.30151134457776363),
 (21, 0.20412414523193154),
 (22, 0.1889822365046136),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0),
 (28, 0.0),
 (29, 0.1889822365046136),
 (30, 0.35355339059327373),
 (31, 0.0),
 (32, 0.0),
 (33, 0.3779644730092272),
 (34, 0.0),
 (35, 0.3779644730092272),
 (36, 0.30151134457776363),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.0),
 (43, 0.5669467095138407),
 (44, 0.35355339059327373),
 (45, 0.0),
 (46, 0.35355339059327373),
 (47, 0.0),
 (48, 0.35355339059327373),
 (49, 0.4082482904638631),
 (50, 0.22360679774997896),
 (51, 0.0),
 (52, 0.1889822365046136),
 (53, 0.0),
 (54, 0.4082482904638631),
 (55, 0.0),
 (56, 0.0),
 (57, 0.20412414523193154),
 (58, 0.0),
 (59, 0.5),
 (60, 0.0),
 (61, 0.20412414523193154),
 (62, 0.3333333333333333),
 (63, 0.0),
 (64, 0.17677669529663687),
 (65, 0.0),
 (66, 0.4472135954999579),
 (67, 0.25),
 (68, 0.5),
 (69, 0.0),
 (70, 0.17677669529663687),
 (71, 0.5),
 (72, 0.4082482904638631),
 (73, 0.16666666666666666),
 (74, 0.0),
 (75, 0.35355339059327373),
 (76, 0.0),
 (77, 0.25),
 (78, 0.25),
 (79, 0.22360679774997896),
 (80, 0.0),
 (81, 0.17677669529663687),
 (82, 0.0),
 (83, 0.0),
 (84, 0.25),
 (85, 0.4082482904638631),
 (86, 0.0),
 (87, 0.0),
 (88, 0.25),
 (89, 0.35355339059327373),
 (90, 0.22360679774997896),
 (91, 0.0),
 (92, 0.0),
 (93, 0.0),
 (94, 0.0),
 (95, 0.0),
 (96, 0.5303300858899106),
 (97, 0.5),
 (98, 0.0),
 (99, 0.2886751345948129),
 (100, 0.0),
 (101, 0.0),
 (102, 0.3779644730092272),
 (103, 0.0),
 (104, 0.0),
 (105, 0.0),
 (106, 0.0),
 (107, 0.4082482904638631),
 (108, 0.2886751345948129),
 (109, 0.3779644730092272),
 (110, 0.0),
 (111, 0.0),
 (112, 0.17677669529663687),
 (113, 0.3779644730092272),
 (114, 0.0),
 (115, 0.0),
 (116, 0.0),
 (117, 0.1889822365046136),
 (118, 0.2886751345948129),
 (119, 0.17677669529663687),
 (120, 0.15811388300841897),
 (121, 0.0),
 (122, 0.0),
 (123, 0.0),
 (124, 0.0),
 (125, 0.1889822365046136),
 (126, 0.0),
 (127, 0.0),
 (128, 0.0),
 (129, 0.15075567228888181),
 (130, 0.0),
 (131, 0.0),
 (132, 0.0),
 (133, 0.0),
 (134, 0.0),
 (135, 0.25),
 (136, 0.0),
 (137, 0.17677669529663687),
 (138, 0.5303300858899106),
 (139, 0.0),
 (140, 0.0),
 (141, 0.22360679774997896),
 (142, 0.0),
 (143, 0.0),
 (144, 0.25),
 (145, 0.0),
 (146, 0.0),
 (147, 0.20412414523193154),
 (148, 0.0),
 (149, 0.35355339059327373),
 (150, 0.0),
 (151, 0.0),
 (152, 0.17677669529663687),
 (153, 0.35355339059327373),
 (154, 0.20412414523193154),
 (155, 0.0),
 (156, 0.0),
 (157, 0.3779644730092272),
 (158, 0.0),
 (159, 0.0),
 (160, 0.4082482904638631),
 (161, 0.0),
 (162, 0.0),
 (163, 0.0),
 (164, 0.25),
 (165, 0.0),
 (166, 0.0),
 (167, 0.4082482904638631),
 (168, 0.0),
 (169, 0.0),
 (170, 0.0),
 (171, 0.15811388300841897),
 (172, 0.0),
 (173, 0.0),
 (174, 0.0),
 (175, 0.0),
 (176, 0.16666666666666666),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.0),
 (182, 0.0),
 (183, 0.0),
 (184, 0.17677669529663687),
 (185, 0.0),
 (186, 0.3779644730092272),
 (187, 0.22360679774997896),
 (188, 0.22360679774997896),
 (189, 0.0),
 (190, 0.0),
 (191, 0.0),
 (192, 0.0),
 (193, 0.0),
 (194, 0.0),
 (195, 0.5303300858899106),
 (196, 0.22360679774997896),
 (197, 0.0),
 (198, 0.20412414523193154),
 (199, 0.0),
 (200, 0.35355339059327373),
 (201, 0.30151134457776363),
 (202, 0.0),
 (203, 0.0),
 (204, 0.0),
 (205, 0.4082482904638631),
 (206, 0.0),
 (207, 0.20412414523193154),
 (208, 0.25),
 (209, 0.0),
 (210, 0.0),
 (211, 0.0),
 (212, 0.20412414523193154),
 (213, 0.0),
 (214, 0.0),
 (215, 0.0),
 (216, 0.0),
 (217, 0.20412414523193154),
 (218, 0.0),
 (219, 0.0),
 (220, 0.20412414523193154),
 (221, 0.22360679774997896),
 (222, 0.4472135954999579),
 (223, 0.0),
 (224, 0.0),
 (225, 0.1889822365046136),
 (226, 0.0),
 (227, 0.0),
 (228, 0.0),
 (229, 0.0),
 (230, 0.0),
 (231, 0.0),
 (232, 0.1889822365046136),
 (233, 0.22360679774997896),
 (234, 0.4472135954999579),
 (235, 0.0),
 (236, 0.0),
 (237, 0.0),
 (238, 0.0),
 (239, 0.0),
 (240, 0.20412414523193154),
 (241, 0.0),
 (242, 0.0),
 (243, 0.0),
 (244, 0.0),
 (245, 0.0),
 (246, 0.20412414523193154),
 (247, 0.0),
 (248, 0.22360679774997896),
 (249, 0.0),
 (250, 0.15811388300841897),
 (251, 0.0),
 (252, 0.0),
 (253, 0.0),
 (254, 0.0),
 (255, 0.0),
 (256, 0.2773500981126146),
 (257, 0.0),
 (258, 0.0),
 (259, 0.0),
 (260, 0.0),
 (261, 0.0),
 (262, 0.0),
 (263, 0.0),
 (264, 0.0),
 (265, 0.0),
 (266, 0.17677669529663687),
 (267, 0.0),
 (268, 0.1889822365046136),
 (269, 0.0),
 (270, 0.0),
 (271, 0.0),
 (272, 0.0),
 (273, 0.0),
 (274, 0.0),
 (275, 0.0),
 (276, 0.0),
 (277, 0.0),
 (278, 0.22360679774997896),
 (279, 0.0),
 (280, 0.0),
 (281, 0.0),
 (282, 0.0),
 (283, 0.17677669529663687),
 (284, 0.25),
 (285, 0.0),
 (286, 0.0),
 (287, 0.0),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (294, 0.0),
 (295, 0.4082482904638631),
 (296, 0.20412414523193154),
 (297, 0.0),
 (298, 0.0),
 (299, 0.25),
 (300, 0.20412414523193154),
 (301, 0.0),
 (302, 0.2886751345948129),
 (303, 0.0),
 (304, 0.0),
 (305, 0.0),
 (306, 0.20412414523193154),
 (307, 0.0),
 (308, 0.1889822365046136),
 (309, 0.0),
 (310, 0.0),
 (311, 0.0),
 (312, 0.0),
 (313, 0.0),
 (314, 0.0),
 (315, 0.3333333333333333),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.0),
 (320, 0.25),
 (321, 0.0),
 (322, 0.22360679774997896),
 (323, 0.0),
 (324, 0.0),
 (325, 0.0),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (329, 0.22360679774997896),
 (330, 0.5),
 (331, 0.20412414523193154),
 (332, 0.0),
 (333, 0.0),
 (334, 0.0),
 (335, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (342, 0.0),
 (343, 0.0),
 (344, 0.0),
 (345, 0.0),
 (346, 0.35355339059327373),
 (347, 0.1889822365046136),
 (348, 0.0),
 (349, 0.17677669529663687),
 (350, 0.25),
 (351, 0.0),
 (352, 0.0),
 (353, 0.4082482904638631),
 (354, 0.0),
 (355, 0.0),
 (356, 0.25),
 (357, 0.0),
 (358, 0.0),
 (359, 0.0),
 (360, 0.0),
 (361, 0.35355339059327373),
 (362, 0.17677669529663687),
 (363, 0.3779644730092272),
 (364, 0.0),
 (365, 0.0),
 (366, 0.35355339059327373),
 (367, 0.1889822365046136),
 (368, 0.0),
 (369, 0.4472135954999579),
 (370, 0.0),
 (371, 0.0),
 (372, 0.17677669529663687),
 (373, 0.0),
 (374, 0.0),
 (375, 0.0),
 (376, 0.0),
 (377, 0.35355339059327373),
 (378, 0.5),
 (379, 0.20412414523193154),
 (380, 0.0),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (384, 0.0),
 (385, 0.0),
 (386, 0.0),
 (387, 0.2886751345948129),
 (388, 0.0),
 (389, 0.0),
 (390, 0.0),
 (391, 0.0),
 (392, 0.0),
 (393, 0.0),
 (394, 0.25),
 (395, 0.0),
 (396, 0.0),
 (397, 0.0),
 (398, 0.30151134457776363),
 (399, 0.4330127018922194),
 (400, 0.0),
 (401, 0.22360679774997896),
 (402, 0.4082482904638631),
 (403, 0.2886751345948129),
 (404, 0.0),
 (405, 0.16666666666666666),
 (406, 0.0),
 (407, 0.0),
 (408, 0.25),
 (409, 0.0),
 (410, 0.5773502691896258),
 (411, 0.4082482904638631),
 (412, 0.0),
 (413, 0.0),
 (414, 0.0),
 (415, 0.0),
 (416, 0.35355339059327373),
 (417, 0.0),
 (418, 0.0),
 (419, 0.0),
 (420, 0.0),
 (421, 0.0),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (429, 0.25),
 (430, 0.0),
 (431, 0.0),
 (432, 0.0),
 (433, 0.0),
 (434, 0.3779644730092272),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (438, 0.0),
 (439, 0.4472135954999579),
 (440, 0.0),
 (441, 0.0),
 (442, 0.0),
 (443, 0.0),
 (444, 0.5303300858899106),
 (445, 0.0),
 (446, 0.0),
 (447, 0.0),
 (448, 0.25),
 (449, 0.0),
 (450, 0.1889822365046136),
 (451, 0.35355339059327373),
 (452, 0.0),
 (453, 0.0),
 (454, 0.0),
 (455, 0.0),
 (456, 0.22360679774997896),
 (457, 0.1889822365046136),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (461, 0.0),
 (462, 0.0),
 (463, 0.4472135954999579),
 (464, 0.0),
 (465, 0.0),
 (466, 0.0),
 (467, 0.0),
 (468, 0.2886751345948129),
 (469, 0.0),
 (470, 0.0),
 (471, 0.35355339059327373),
 (472, 0.0),
 (473, 0.0),
 (474, 0.0),
 (475, 0.0),
 (476, 0.0),
 (477, 0.2886751345948129),
 (478, 0.0),
 (479, 0.2886751345948129),
 (480, 0.0),
 (481, 0.0),
 (482, 0.1889822365046136),
 (483, 0.0),
 (484, 0.0),
 (485, 0.0),
 (486, 0.0),
 (487, 0.0),
 (488, 0.0),
 (489, 0.0),
 (490, 0.20412414523193154),
 (491, 0.0),
 (492, 0.0),
 (493, 0.25),
 (494, 0.0),
 (495, 0.20412414523193154),
 (496, 0.0),
 (497, 0.0),
 (498, 0.20412414523193154),
 (499, 0.0),
 (500, 0.25),
 (501, 0.22360679774997896),
 (502, 0.0),
 (503, 0.0),
 (504, 0.20412414523193154),
 (505, 0.0),
 (506, 0.0),
 (507, 0.0),
 (508, 0.0),
 (509, 0.20412414523193154),
 (510, 0.3779644730092272),
 (511, 0.0),
 (512, 0.0),
 (513, 0.1889822365046136),
 (514, 0.5),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.0),
 (524, 0.0),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0),
 (529, 0.1889822365046136),
 (530, 0.0),
 (531, 0.0),
 (532, 0.0),
 (533, 0.25),
 (534, 0.20412414523193154),
 (535, 0.0),
 (536, 0.0),
 (537, 0.0),
 (538, 0.2886751345948129),
 (539, 0.0),
 (540, 0.0),
 (541, 0.1889822365046136),
 (542, 0.20412414523193154),
 (543, 0.0),
 (544, 0.0),
 (545, 0.0),
 (546, 0.0),
 (547, 0.0),
 (548, 0.0),
 (549, 0.0),
 (550, 0.0),
 (551, 0.22360679774997896),
 (552, 0.0),
 (553, 0.0),
 (554, 0.0),
 (555, 0.20412414523193154),
 (556, 0.0),
 (557, 0.0),
 (558, 0.1889822365046136),
 (559, 0.25),
 (560, 0.0),
 (561, 0.0),
 (562, 0.20412414523193154),
 (563, 0.0),
 (564, 0.1889822365046136),
 (565, 0.0),
 (566, 0.35355339059327373),
 (567, 0.0),
 (568, 0.0),
 (569, 0.0),
 (570, 0.25),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.0),
 (577, 0.0),
 (578, 0.0),
 (579, 0.0),
 (580, 0.20412414523193154),
 (581, 0.0),
 (582, 0.0),
 (583, 0.2886751345948129),
 (584, 0.0),
 (585, 0.20412414523193154),
 (586, 0.0),
 (587, 0.0),
 (588, 0.1889822365046136),
 (589, 0.0),
 (590, 0.0),
 (591, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.0),
 (595, 0.0),
 (596, 0.0),
 (597, 0.0),
 (598, 0.25),
 (599, 0.0),
 (600, 0.17677669529663687),
 (601, 0.16666666666666666),
 (602, 0.0),
 (603, 0.0),
 (604, 0.22360679774997896),
 (605, 0.0),
 (606, 0.0),
 (607, 0.20412414523193154),
 (608, 0.0),
 (609, 0.0),
 (610, 0.0),
 (611, 0.0),
 (612, 0.0),
 (613, 0.0),
 (614, 0.0),
 (615, 0.0),
 (616, 0.0),
 (617, 0.0),
 (618, 0.3333333333333333),
 (619, 0.0),
 (620, 0.0),
 (621, 0.0),
 (622, 0.0),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (626, 0.22360679774997896),
 (627, 0.0),
 (628, 0.35355339059327373),
 (629, 0.0),
 (630, 0.0),
 (631, 0.0),
 (632, 0.22360679774997896),
 (633, 0.0),
 (634, 0.0),
 (635, 0.0),
 (636, 0.0),
 (637, 0.22360679774997896),
 (638, 0.0),
 (639, 0.0),
 (640, 0.0),
 (641, 0.22360679774997896),
 (642, 0.0),
 (643, 0.0),
 (644, 0.0),
 (645, 0.0),
 (646, 0.0),
 (647, 0.5),
 (648, 0.2886751345948129),
 (649, 0.0),
 (650, 0.3779644730092272),
 (651, 0.0),
 (652, 0.2886751345948129),
 (653, 0.0),
 (654, 0.20412414523193154),
 (655, 0.20412414523193154),
 (656, 0.0),
 (657, 0.0),
 (658, 0.22360679774997896),
 (659, 0.0),
 (660, 0.0),
 (661, 0.0),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0),
 (665, 0.0),
 (666, 0.22360679774997896),
 (667, 0.0),
 (668, 0.0),
 (669, 0.0),
 (670, 0.0),
 (671, 0.0),
 (672, 0.0),
 (673, 0.0),
 (674, 0.0),
 (675, 0.0),
 (676, 0.0),
 (677, 0.1889822365046136),
 (678, 0.0),
 (679, 0.0),
 (680, 0.0),
 (681, 0.0),
 (682, 0.0),
 (683, 0.31622776601683794),
 (684, 0.0),
 (685, 0.0),
 (686, 0.0),
 (687, 0.0),
 (688, 0.0),
 (689, 0.0),
 (690, 0.0),
 (691, 0.22360679774997896),
 (692, 0.0),
 (693, 0.0),
 (694, 0.25),
 (695, 0.0),
 (696, 0.25),
 (697, 0.22360679774997896),
 (698, 0.0),
 (699, 0.20412414523193154),
 (700, 0.0),
 (701, 0.0),
 (702, 0.20412414523193154),
 (703, 0.0),
 (704, 0.22360679774997896),
 (705, 0.0),
 (706, 0.22360679774997896),
 (707, 0.0),
 (708, 0.35355339059327373),
 (709, 0.30151134457776363),
 (710, 0.0),
 (711, 0.0),
 (712, 0.0),
 (713, 0.0),
 (714, 0.0),
 (715, 0.22360679774997896),
 (716, 0.0),
 (717, 0.0),
 (718, 0.0),
 (719, 0.0),
 (720, 0.0),
 (721, 0.0),
 (722, 0.0),
 (723, 0.0),
 (724, 0.0),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0),
 (728, 0.0),
 (729, 0.0),
 (730, 0.0),
 (731, 0.0),
 (732, 0.0),
 (733, 0.0),
 (734, 0.20412414523193154),
 (735, 0.17677669529663687),
 (736, 0.0),
 (737, 0.0),
 (738, 0.5),
 (739, 0.0),
 (740, 0.0),
 (741, 0.0),
 (742, 0.17677669529663687),
 (743, 0.0),
 (744, 0.0),
 (745, 0.2886751345948129),
 (746, 0.0),
 (747, 0.0),
 (748, 0.0),
 (749, 0.0),
 (750, 0.0),
 (751, 0.0),
 (752, 0.0),
 (753, 0.0),
 (754, 0.0),
 (755, 0.0),
 (756, 0.22360679774997896),
 (757, 0.0),
 (758, 0.1889822365046136),
 (759, 0.0),
 (760, 0.22360679774997896),
 (761, 0.0),
 (762, 0.0),
 (763, 0.0),
 (764, 0.25),
 (765, 0.0),
 (766, 0.4472135954999579),
 (767, 0.0),
 (768, 0.0),
 (769, 0.25),
 (770, 0.0),
 (771, 0.0),
 (772, 0.0),
 (773, 0.0),
 (774, 0.22360679774997896),
 (775, 0.0),
 (776, 0.20412414523193154),
 (777, 0.2886751345948129),
 (778, 0.0),
 (779, 0.0),
 (780, 0.0),
 (781, 0.0),
 (782, 0.0),
 (783, 0.0),
 (784, 0.0),
 (785, 0.0),
 (786, 0.0),
 (787, 0.0),
 (788, 0.0),
 (789, 0.0),
 (790, 0.22360679774997896),
 (791, 0.0),
 (792, 0.0),
 (793, 0.1889822365046136),
 (794, 0.35355339059327373),
 (795, 0.0),
 (796, 0.0),
 (797, 0.20412414523193154),
 (798, 0.3779644730092272),
 (799, 0.0),
 (800, 0.0),
 (801, 0.0),
 (802, 0.4082482904638631),
 (803, 0.5303300858899106),
 (804, 0.0),
 (805, 0.0),
 (806, 0.0),
 (807, 0.0),
 (808, 0.0),
 (809, 0.20412414523193154),
 (810, 0.0),
 (811, 0.45226701686664544),
 (812, 0.0),
 (813, 0.0),
 (814, 0.0),
 (815, 0.25),
 (816, 0.0),
 (817, 0.0),
 (818, 0.0),
 (819, 0.0),
 (820, 0.0),
 (821, 0.0),
 (822, 0.0),
 (823, 0.2886751345948129),
 (824, 0.0),
 (825, 0.0),
 (826, 0.0),
 (827, 0.0),
 (828, 0.0),
 (829, 0.4472135954999579),
 (830, 0.0),
 (831, 0.0),
 (832, 0.0),
 (833, 0.2886751345948129),
 (834, 0.22360679774997896),
 (835, 0.0),
 (836, 0.0),
 (837, 0.0),
 (838, 0.0),
 (839, 0.0),
 (840, 0.0),
 (841, 0.0),
 (842, 0.0),
 (843, 0.0),
 (844, 0.2886751345948129),
 (845, 0.17677669529663687),
 (846, 0.0),
 (847, 0.0),
 (848, 0.0),
 (849, 0.0),
 (850, 0.0),
 (851, 0.0),
 (852, 0.0),
 (853, 0.0),
 (854, 0.0),
 (855, 0.0),
 (856, 0.1889822365046136),
 (857, 0.22360679774997896),
 (858, 0.0),
 (859, 0.0),
 (860, 0.0),
 (861, 0.0),
 (862, 0.0),
 (863, 0.2886751345948129),
 (864, 0.35355339059327373),
 (865, 0.0),
 (866, 0.0),
 (867, 0.22360679774997896),
 (868, 0.0),
 (869, 0.0),
 (870, 0.0),
 (871, 0.0),
 (872, 0.0),
 (873, 0.0),
 (874, 0.1889822365046136),
 (875, 0.0),
 (876, 0.0),
 (877, 0.0),
 (878, 0.0),
 (879, 0.0),
 (880, 0.20412414523193154),
 (881, 0.0),
 (882, 0.0),
 (883, 0.2886751345948129),
 (884, 0.0),
 (885, 0.0),
 (886, 0.0),
 (887, 0.0),
 (888, 0.0),
 (889, 0.0),
 (890, 0.0),
 (891, 0.0),
 (892, 0.0),
 (893, 0.0),
 (894, 0.0),
 (895, 0.0),
 (896, 0.0),
 (897, 0.0),
 (898, 0.0),
 (899, 0.1889822365046136),
 (900, 0.3779644730092272),
 (901, 0.0),
 (902, 0.0),
 (903, 0.0),
 (904, 0.1889822365046136),
 (905, 0.0),
 (906, 0.0),
 (907, 0.0),
 (908, 0.0),
 (909, 0.35355339059327373),
 (910, 0.0),
 (911, 0.0),
 (912, 0.0),
 (913, 0.0),
 (914, 0.0),
 (915, 0.0),
 (916, 0.0),
 (917, 0.0),
 (918, 0.0),
 (919, 0.0),
 (920, 0.0),
 (921, 0.25),
 (922, 0.0),
 (923, 0.0),
 (924, 0.0),
 (925, 0.0),
 (926, 0.0),
 (927, 0.0),
 (928, 0.0),
 (929, 0.0),
 (930, 0.0),
 (931, 0.0),
 (932, 0.0),
 (933, 0.0),
 (934, 0.0),
 (935, 0.0),
 (936, 0.0),
 (937, 0.0),
 (938, 0.0),
 (939, 0.0),
 (940, 0.22360679774997896),
 (941, 0.0),
 (942, 0.0),
 (943, 0.0),
 (944, 0.0),
 (945, 0.0),
 (946, 0.0),
 (947, 0.5),
 (948, 0.2886751345948129),
 (949, 0.0),
 (950, 0.0),
 (951, 0.0),
 (952, 0.0),
 (953, 0.4082482904638631),
 (954, 0.35355339059327373),
 (955, 0.0),
 (956, 0.4082482904638631),
 (957, 0.1889822365046136),
 (958, 0.20412414523193154),
 (959, 0.0),
 (960, 0.1889822365046136),
 (961, 0.0),
 (962, 0.2886751345948129),
 (963, 0.35355339059327373),
 (964, 0.1889822365046136),
 (965, 0.22360679774997896),
 (966, 0.0),
 (967, 0.0),
 (968, 0.0),
 (969, 0.0),
 (970, 0.0),
 (971, 0.0),
 (972, 0.20412414523193154),
 (973, 0.0),
 (974, 0.0),
 (975, 0.0),
 (976, 0.0),
 (977, 0.0),
 (978, 0.0),
 (979, 0.0),
 (980, 0.0),
 (981, 0.0),
 (982, 0.0),
 (983, 0.0),
 (984, 0.0),
 (985, 0.0),
 (986, 0.0),
 (987, 0.0),
 (988, 0.0),
 (989, 0.0),
 (990, 0.0),
 (991, 0.5),
 (992, 0.0),
 (993, 0.0),
 (994, 0.0),
 (995, 0.0),
 (996, 0.0),
 (997, 0.16666666666666666),
 (998, 0.0),
 (999, 0.0),
 ...]

In [32]:
sortedscore = sorted(scores,key = lambda x:x[1],reverse=True)
sortedscore

[(4, 1.0),
 (410, 0.5773502691896258),
 (43, 0.5669467095138407),
 (96, 0.5303300858899106),
 (138, 0.5303300858899106),
 (195, 0.5303300858899106),
 (444, 0.5303300858899106),
 (803, 0.5303300858899106),
 (11, 0.5),
 (59, 0.5),
 (68, 0.5),
 (71, 0.5),
 (97, 0.5),
 (330, 0.5),
 (378, 0.5),
 (514, 0.5),
 (647, 0.5),
 (738, 0.5),
 (947, 0.5),
 (991, 0.5),
 (811, 0.45226701686664544),
 (66, 0.4472135954999579),
 (222, 0.4472135954999579),
 (234, 0.4472135954999579),
 (369, 0.4472135954999579),
 (439, 0.4472135954999579),
 (463, 0.4472135954999579),
 (766, 0.4472135954999579),
 (829, 0.4472135954999579),
 (399, 0.4330127018922194),
 (49, 0.4082482904638631),
 (54, 0.4082482904638631),
 (72, 0.4082482904638631),
 (85, 0.4082482904638631),
 (107, 0.4082482904638631),
 (160, 0.4082482904638631),
 (167, 0.4082482904638631),
 (205, 0.4082482904638631),
 (295, 0.4082482904638631),
 (353, 0.4082482904638631),
 (402, 0.4082482904638631),
 (411, 0.4082482904638631),
 (802, 0.4082482904638631),
 (953, 0.4082482904638631),
 (956, 0.4082482904638631),
 (1002, 0.4082482904638631),
 (8, 0.3779644730092272),
 (33, 0.3779644730092272),
 (35, 0.3779644730092272),
 (102, 0.3779644730092272),
 (109, 0.3779644730092272),
 (113, 0.3779644730092272),
 (157, 0.3779644730092272),
 (186, 0.3779644730092272),
 (363, 0.3779644730092272),
 (434, 0.3779644730092272),
 (510, 0.3779644730092272),
 (650, 0.3779644730092272),
 (798, 0.3779644730092272),
 (900, 0.3779644730092272),
 (14, 0.35355339059327373),
 (30, 0.35355339059327373),
 (44, 0.35355339059327373),
 (46, 0.35355339059327373),
 (48, 0.35355339059327373),
 (75, 0.35355339059327373),
 (89, 0.35355339059327373),
 (149, 0.35355339059327373),
 (153, 0.35355339059327373),
 (200, 0.35355339059327373),
 (346, 0.35355339059327373),
 (361, 0.35355339059327373),
 (366, 0.35355339059327373),
 (377, 0.35355339059327373),
 (416, 0.35355339059327373),
 (451, 0.35355339059327373),
 (471, 0.35355339059327373),
 (566, 0.35355339059327373),
 (628, 0.35355339059327373),
 (708, 0.35355339059327373),
 (794, 0.35355339059327373),
 (864, 0.35355339059327373),
 (909, 0.35355339059327373),
 (954, 0.35355339059327373),
 (963, 0.35355339059327373),
 (1023, 0.35355339059327373),
 (1112, 0.35355339059327373),
 (1115, 0.35355339059327373),
 (1134, 0.35355339059327373),
 (1136, 0.35355339059327373),
 (1141, 0.35355339059327373),
 (1151, 0.35355339059327373),
 (62, 0.3333333333333333),
 (315, 0.3333333333333333),
 (618, 0.3333333333333333),
 (683, 0.31622776601683794),
 (20, 0.30151134457776363),
 (36, 0.30151134457776363),
 (201, 0.30151134457776363),
 (398, 0.30151134457776363),
 (709, 0.30151134457776363),
 (99, 0.2886751345948129),
 (108, 0.2886751345948129),
 (118, 0.2886751345948129),
 (302, 0.2886751345948129),
 (387, 0.2886751345948129),
 (403, 0.2886751345948129),
 (468, 0.2886751345948129),
 (477, 0.2886751345948129),
 (479, 0.2886751345948129),
 (538, 0.2886751345948129),
 (583, 0.2886751345948129),
 (648, 0.2886751345948129),
 (652, 0.2886751345948129),
 (745, 0.2886751345948129),
 (777, 0.2886751345948129),
 (823, 0.2886751345948129),
 (833, 0.2886751345948129),
 (844, 0.2886751345948129),
 (863, 0.2886751345948129),
 (883, 0.2886751345948129),
 (948, 0.2886751345948129),
 (962, 0.2886751345948129),
 (1005, 0.2886751345948129),
 (1089, 0.2886751345948129),
 (1171, 0.2886751345948129),
 (256, 0.2773500981126146),
 (67, 0.25),
 (77, 0.25),
 (78, 0.25),
 (84, 0.25),
 (88, 0.25),
 (135, 0.25),
 (144, 0.25),
 (164, 0.25),
 (208, 0.25),
 (284, 0.25),
 (299, 0.25),
 (320, 0.25),
 (350, 0.25),
 (356, 0.25),
 (394, 0.25),
 (408, 0.25),
 (429, 0.25),
 (448, 0.25),
 (493, 0.25),
 (500, 0.25),
 (533, 0.25),
 (559, 0.25),
 (570, 0.25),
 (598, 0.25),
 (694, 0.25),
 (696, 0.25),
 (764, 0.25),
 (769, 0.25),
 (815, 0.25),
 (921, 0.25),
 (1012, 0.25),
 (1021, 0.25),
 (1135, 0.25),
 (18, 0.22360679774997896),
 (50, 0.22360679774997896),
 (79, 0.22360679774997896),
 (90, 0.22360679774997896),
 (141, 0.22360679774997896),
 (187, 0.22360679774997896),
 (188, 0.22360679774997896),
 (196, 0.22360679774997896),
 (221, 0.22360679774997896),
 (233, 0.22360679774997896),
 (248, 0.22360679774997896),
 (278, 0.22360679774997896),
 (322, 0.22360679774997896),
 (329, 0.22360679774997896),
 (401, 0.22360679774997896),
 (456, 0.22360679774997896),
 (501, 0.22360679774997896),
 (551, 0.22360679774997896),
 (604, 0.22360679774997896),
 (626, 0.22360679774997896),
 (632, 0.22360679774997896),
 (637, 0.22360679774997896),
 (641, 0.22360679774997896),
 (658, 0.22360679774997896),
 (666, 0.22360679774997896),
 (691, 0.22360679774997896),
 (697, 0.22360679774997896),
 (704, 0.22360679774997896),
 (706, 0.22360679774997896),
 (715, 0.22360679774997896),
 (756, 0.22360679774997896),
 (760, 0.22360679774997896),
 (774, 0.22360679774997896),
 (790, 0.22360679774997896),
 (834, 0.22360679774997896),
 (857, 0.22360679774997896),
 (867, 0.22360679774997896),
 (940, 0.22360679774997896),
 (965, 0.22360679774997896),
 (1043, 0.22360679774997896),
 (1054, 0.22360679774997896),
 (1091, 0.22360679774997896),
 (1100, 0.22360679774997896),
 (1122, 0.22360679774997896),
 (1124, 0.22360679774997896),
 (1166, 0.22360679774997896),
 (1181, 0.22360679774997896),
 (5, 0.20412414523193154),
 (6, 0.20412414523193154),
 (10, 0.20412414523193154),
 (21, 0.20412414523193154),
 (57, 0.20412414523193154),
 (61, 0.20412414523193154),
 (147, 0.20412414523193154),
 (154, 0.20412414523193154),
 (198, 0.20412414523193154),
 (207, 0.20412414523193154),
 (212, 0.20412414523193154),
 (217, 0.20412414523193154),
 (220, 0.20412414523193154),
 (240, 0.20412414523193154),
 (246, 0.20412414523193154),
 (296, 0.20412414523193154),
 (300, 0.20412414523193154),
 (306, 0.20412414523193154),
 (331, 0.20412414523193154),
 (379, 0.20412414523193154),
 (490, 0.20412414523193154),
 (495, 0.20412414523193154),
 (498, 0.20412414523193154),
 (504, 0.20412414523193154),
 (509, 0.20412414523193154),
 (534, 0.20412414523193154),
 (542, 0.20412414523193154),
 (555, 0.20412414523193154),
 (562, 0.20412414523193154),
 (580, 0.20412414523193154),
 (585, 0.20412414523193154),
 (607, 0.20412414523193154),
 (654, 0.20412414523193154),
 (655, 0.20412414523193154),
 (699, 0.20412414523193154),
 (702, 0.20412414523193154),
 (734, 0.20412414523193154),
 (776, 0.20412414523193154),
 (797, 0.20412414523193154),
 (809, 0.20412414523193154),
 (880, 0.20412414523193154),
 (958, 0.20412414523193154),
 (972, 0.20412414523193154),
 (1093, 0.20412414523193154),
 (1123, 0.20412414523193154),
 (1127, 0.20412414523193154),
 (1140, 0.20412414523193154),
 (1161, 0.20412414523193154),
 (7, 0.1889822365046136),
 (17, 0.1889822365046136),
 (22, 0.1889822365046136),
 (29, 0.1889822365046136),
 (52, 0.1889822365046136),
 (117, 0.1889822365046136),
 (125, 0.1889822365046136),
 (225, 0.1889822365046136),
 (232, 0.1889822365046136),
 (268, 0.1889822365046136),
 (308, 0.1889822365046136),
 (347, 0.1889822365046136),
 (367, 0.1889822365046136),
 (450, 0.1889822365046136),
 (457, 0.1889822365046136),
 (482, 0.1889822365046136),
 (513, 0.1889822365046136),
 (529, 0.1889822365046136),
 (541, 0.1889822365046136),
 (558, 0.1889822365046136),
 (564, 0.1889822365046136),
 (588, 0.1889822365046136),
 (677, 0.1889822365046136),
 (758, 0.1889822365046136),
 (793, 0.1889822365046136),
 (856, 0.1889822365046136),
 (874, 0.1889822365046136),
 (899, 0.1889822365046136),
 (904, 0.1889822365046136),
 (957, 0.1889822365046136),
 (960, 0.1889822365046136),
 (964, 0.1889822365046136),
 (1008, 0.1889822365046136),
 (1032, 0.1889822365046136),
 (1132, 0.1889822365046136),
 (1133, 0.1889822365046136),
 (1165, 0.1889822365046136),
 (1177, 0.1889822365046136),
 (3162, 0.1889822365046136),
 (13, 0.17677669529663687),
 (64, 0.17677669529663687),
 (70, 0.17677669529663687),
 (81, 0.17677669529663687),
 (112, 0.17677669529663687),
 (119, 0.17677669529663687),
 (137, 0.17677669529663687),
 (152, 0.17677669529663687),
 (184, 0.17677669529663687),
 (266, 0.17677669529663687),
 (283, 0.17677669529663687),
 (349, 0.17677669529663687),
 (362, 0.17677669529663687),
 (372, 0.17677669529663687),
 (600, 0.17677669529663687),
 (735, 0.17677669529663687),
 (742, 0.17677669529663687),
 (845, 0.17677669529663687),
 (1051, 0.17677669529663687),
 (1065, 0.17677669529663687),
 (73, 0.16666666666666666),
 (176, 0.16666666666666666),
 (405, 0.16666666666666666),
 (601, 0.16666666666666666),
 (997, 0.16666666666666666),
 (1131, 0.16666666666666666),
 (120, 0.15811388300841897),
 (171, 0.15811388300841897),
 (250, 0.15811388300841897),
 (1074, 0.15811388300841897),
 (129, 0.15075567228888181),
 (1031, 0.14433756729740646),
 (1156, 0.14433756729740646),
 (0, 0.0),
 (1, 0.0),
 (2, 0.0),
 (3, 0.0),
 (9, 0.0),
 (12, 0.0),
 (15, 0.0),
 (16, 0.0),
 (19, 0.0),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0),
 (28, 0.0),
 (31, 0.0),
 (32, 0.0),
 (34, 0.0),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.0),
 (45, 0.0),
 (47, 0.0),
 (51, 0.0),
 (53, 0.0),
 (55, 0.0),
 (56, 0.0),
 (58, 0.0),
 (60, 0.0),
 (63, 0.0),
 (65, 0.0),
 (69, 0.0),
 (74, 0.0),
 (76, 0.0),
 (80, 0.0),
 (82, 0.0),
 (83, 0.0),
 (86, 0.0),
 (87, 0.0),
 (91, 0.0),
 (92, 0.0),
 (93, 0.0),
 (94, 0.0),
 (95, 0.0),
 (98, 0.0),
 (100, 0.0),
 (101, 0.0),
 (103, 0.0),
 (104, 0.0),
 (105, 0.0),
 (106, 0.0),
 (110, 0.0),
 (111, 0.0),
 (114, 0.0),
 (115, 0.0),
 (116, 0.0),
 (121, 0.0),
 (122, 0.0),
 (123, 0.0),
 (124, 0.0),
 (126, 0.0),
 (127, 0.0),
 (128, 0.0),
 (130, 0.0),
 (131, 0.0),
 (132, 0.0),
 (133, 0.0),
 (134, 0.0),
 (136, 0.0),
 (139, 0.0),
 (140, 0.0),
 (142, 0.0),
 (143, 0.0),
 (145, 0.0),
 (146, 0.0),
 (148, 0.0),
 (150, 0.0),
 (151, 0.0),
 (155, 0.0),
 (156, 0.0),
 (158, 0.0),
 (159, 0.0),
 (161, 0.0),
 (162, 0.0),
 (163, 0.0),
 (165, 0.0),
 (166, 0.0),
 (168, 0.0),
 (169, 0.0),
 (170, 0.0),
 (172, 0.0),
 (173, 0.0),
 (174, 0.0),
 (175, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.0),
 (182, 0.0),
 (183, 0.0),
 (185, 0.0),
 (189, 0.0),
 (190, 0.0),
 (191, 0.0),
 (192, 0.0),
 (193, 0.0),
 (194, 0.0),
 (197, 0.0),
 (199, 0.0),
 (202, 0.0),
 (203, 0.0),
 (204, 0.0),
 (206, 0.0),
 (209, 0.0),
 (210, 0.0),
 (211, 0.0),
 (213, 0.0),
 (214, 0.0),
 (215, 0.0),
 (216, 0.0),
 (218, 0.0),
 (219, 0.0),
 (223, 0.0),
 (224, 0.0),
 (226, 0.0),
 (227, 0.0),
 (228, 0.0),
 (229, 0.0),
 (230, 0.0),
 (231, 0.0),
 (235, 0.0),
 (236, 0.0),
 (237, 0.0),
 (238, 0.0),
 (239, 0.0),
 (241, 0.0),
 (242, 0.0),
 (243, 0.0),
 (244, 0.0),
 (245, 0.0),
 (247, 0.0),
 (249, 0.0),
 (251, 0.0),
 (252, 0.0),
 (253, 0.0),
 (254, 0.0),
 (255, 0.0),
 (257, 0.0),
 (258, 0.0),
 (259, 0.0),
 (260, 0.0),
 (261, 0.0),
 (262, 0.0),
 (263, 0.0),
 (264, 0.0),
 (265, 0.0),
 (267, 0.0),
 (269, 0.0),
 (270, 0.0),
 (271, 0.0),
 (272, 0.0),
 (273, 0.0),
 (274, 0.0),
 (275, 0.0),
 (276, 0.0),
 (277, 0.0),
 (279, 0.0),
 (280, 0.0),
 (281, 0.0),
 (282, 0.0),
 (285, 0.0),
 (286, 0.0),
 (287, 0.0),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (294, 0.0),
 (297, 0.0),
 (298, 0.0),
 (301, 0.0),
 (303, 0.0),
 (304, 0.0),
 (305, 0.0),
 (307, 0.0),
 (309, 0.0),
 (310, 0.0),
 (311, 0.0),
 (312, 0.0),
 (313, 0.0),
 (314, 0.0),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.0),
 (321, 0.0),
 (323, 0.0),
 (324, 0.0),
 (325, 0.0),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (332, 0.0),
 (333, 0.0),
 (334, 0.0),
 (335, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (342, 0.0),
 (343, 0.0),
 (344, 0.0),
 (345, 0.0),
 (348, 0.0),
 (351, 0.0),
 (352, 0.0),
 (354, 0.0),
 (355, 0.0),
 (357, 0.0),
 (358, 0.0),
 (359, 0.0),
 (360, 0.0),
 (364, 0.0),
 (365, 0.0),
 (368, 0.0),
 (370, 0.0),
 (371, 0.0),
 (373, 0.0),
 (374, 0.0),
 (375, 0.0),
 (376, 0.0),
 (380, 0.0),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (384, 0.0),
 (385, 0.0),
 (386, 0.0),
 (388, 0.0),
 (389, 0.0),
 (390, 0.0),
 (391, 0.0),
 (392, 0.0),
 (393, 0.0),
 (395, 0.0),
 (396, 0.0),
 (397, 0.0),
 (400, 0.0),
 (404, 0.0),
 (406, 0.0),
 (407, 0.0),
 (409, 0.0),
 (412, 0.0),
 (413, 0.0),
 (414, 0.0),
 (415, 0.0),
 (417, 0.0),
 (418, 0.0),
 (419, 0.0),
 (420, 0.0),
 (421, 0.0),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (430, 0.0),
 (431, 0.0),
 (432, 0.0),
 (433, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (438, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.0),
 (443, 0.0),
 (445, 0.0),
 (446, 0.0),
 (447, 0.0),
 (449, 0.0),
 (452, 0.0),
 (453, 0.0),
 (454, 0.0),
 (455, 0.0),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (461, 0.0),
 (462, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.0),
 (467, 0.0),
 (469, 0.0),
 (470, 0.0),
 (472, 0.0),
 (473, 0.0),
 (474, 0.0),
 (475, 0.0),
 (476, 0.0),
 (478, 0.0),
 (480, 0.0),
 (481, 0.0),
 (483, 0.0),
 (484, 0.0),
 (485, 0.0),
 (486, 0.0),
 (487, 0.0),
 (488, 0.0),
 (489, 0.0),
 (491, 0.0),
 (492, 0.0),
 (494, 0.0),
 (496, 0.0),
 (497, 0.0),
 (499, 0.0),
 (502, 0.0),
 (503, 0.0),
 (505, 0.0),
 (506, 0.0),
 (507, 0.0),
 (508, 0.0),
 (511, 0.0),
 (512, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.0),
 (524, 0.0),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0),
 (530, 0.0),
 (531, 0.0),
 (532, 0.0),
 (535, 0.0),
 (536, 0.0),
 (537, 0.0),
 (539, 0.0),
 (540, 0.0),
 (543, 0.0),
 (544, 0.0),
 (545, 0.0),
 (546, 0.0),
 (547, 0.0),
 (548, 0.0),
 (549, 0.0),
 (550, 0.0),
 (552, 0.0),
 (553, 0.0),
 (554, 0.0),
 (556, 0.0),
 (557, 0.0),
 (560, 0.0),
 (561, 0.0),
 (563, 0.0),
 (565, 0.0),
 (567, 0.0),
 (568, 0.0),
 (569, 0.0),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.0),
 (577, 0.0),
 (578, 0.0),
 (579, 0.0),
 (581, 0.0),
 (582, 0.0),
 (584, 0.0),
 (586, 0.0),
 (587, 0.0),
 (589, 0.0),
 (590, 0.0),
 (591, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.0),
 (595, 0.0),
 (596, 0.0),
 (597, 0.0),
 (599, 0.0),
 (602, 0.0),
 (603, 0.0),
 (605, 0.0),
 (606, 0.0),
 (608, 0.0),
 (609, 0.0),
 (610, 0.0),
 (611, 0.0),
 (612, 0.0),
 (613, 0.0),
 (614, 0.0),
 (615, 0.0),
 (616, 0.0),
 (617, 0.0),
 (619, 0.0),
 (620, 0.0),
 (621, 0.0),
 (622, 0.0),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (627, 0.0),
 (629, 0.0),
 (630, 0.0),
 (631, 0.0),
 (633, 0.0),
 (634, 0.0),
 (635, 0.0),
 (636, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.0),
 (642, 0.0),
 (643, 0.0),
 (644, 0.0),
 (645, 0.0),
 (646, 0.0),
 (649, 0.0),
 (651, 0.0),
 (653, 0.0),
 (656, 0.0),
 (657, 0.0),
 (659, 0.0),
 (660, 0.0),
 (661, 0.0),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0),
 (665, 0.0),
 (667, 0.0),
 (668, 0.0),
 (669, 0.0),
 (670, 0.0),
 (671, 0.0),
 (672, 0.0),
 (673, 0.0),
 (674, 0.0),
 (675, 0.0),
 (676, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.0),
 (681, 0.0),
 (682, 0.0),
 (684, 0.0),
 (685, 0.0),
 (686, 0.0),
 (687, 0.0),
 (688, 0.0),
 (689, 0.0),
 (690, 0.0),
 (692, 0.0),
 (693, 0.0),
 (695, 0.0),
 (698, 0.0),
 (700, 0.0),
 (701, 0.0),
 (703, 0.0),
 (705, 0.0),
 (707, 0.0),
 (710, 0.0),
 (711, 0.0),
 (712, 0.0),
 (713, 0.0),
 (714, 0.0),
 (716, 0.0),
 (717, 0.0),
 (718, 0.0),
 (719, 0.0),
 (720, 0.0),
 (721, 0.0),
 (722, 0.0),
 (723, 0.0),
 (724, 0.0),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0),
 (728, 0.0),
 (729, 0.0),
 (730, 0.0),
 (731, 0.0),
 (732, 0.0),
 (733, 0.0),
 (736, 0.0),
 (737, 0.0),
 (739, 0.0),
 (740, 0.0),
 (741, 0.0),
 (743, 0.0),
 (744, 0.0),
 (746, 0.0),
 (747, 0.0),
 (748, 0.0),
 (749, 0.0),
 (750, 0.0),
 (751, 0.0),
 (752, 0.0),
 (753, 0.0),
 (754, 0.0),
 (755, 0.0),
 (757, 0.0),
 (759, 0.0),
 (761, 0.0),
 (762, 0.0),
 (763, 0.0),
 (765, 0.0),
 (767, 0.0),
 (768, 0.0),
 (770, 0.0),
 (771, 0.0),
 (772, 0.0),
 (773, 0.0),
 (775, 0.0),
 (778, 0.0),
 (779, 0.0),
 (780, 0.0),
 (781, 0.0),
 (782, 0.0),
 (783, 0.0),
 (784, 0.0),
 (785, 0.0),
 (786, 0.0),
 (787, 0.0),
 (788, 0.0),
 (789, 0.0),
 (791, 0.0),
 (792, 0.0),
 (795, 0.0),
 (796, 0.0),
 (799, 0.0),
 (800, 0.0),
 (801, 0.0),
 (804, 0.0),
 (805, 0.0),
 (806, 0.0),
 (807, 0.0),
 (808, 0.0),
 (810, 0.0),
 (812, 0.0),
 (813, 0.0),
 (814, 0.0),
 (816, 0.0),
 (817, 0.0),
 (818, 0.0),
 (819, 0.0),
 (820, 0.0),
 (821, 0.0),
 (822, 0.0),
 (824, 0.0),
 (825, 0.0),
 (826, 0.0),
 (827, 0.0),
 (828, 0.0),
 (830, 0.0),
 (831, 0.0),
 (832, 0.0),
 (835, 0.0),
 (836, 0.0),
 (837, 0.0),
 (838, 0.0),
 (839, 0.0),
 (840, 0.0),
 (841, 0.0),
 (842, 0.0),
 (843, 0.0),
 (846, 0.0),
 (847, 0.0),
 (848, 0.0),
 (849, 0.0),
 (850, 0.0),
 (851, 0.0),
 (852, 0.0),
 (853, 0.0),
 (854, 0.0),
 (855, 0.0),
 (858, 0.0),
 (859, 0.0),
 (860, 0.0),
 (861, 0.0),
 (862, 0.0),
 (865, 0.0),
 (866, 0.0),
 (868, 0.0),
 (869, 0.0),
 (870, 0.0),
 (871, 0.0),
 (872, 0.0),
 (873, 0.0),
 (875, 0.0),
 (876, 0.0),
 (877, 0.0),
 (878, 0.0),
 (879, 0.0),
 (881, 0.0),
 (882, 0.0),
 (884, 0.0),
 (885, 0.0),
 (886, 0.0),
 (887, 0.0),
 (888, 0.0),
 (889, 0.0),
 (890, 0.0),
 (891, 0.0),
 (892, 0.0),
 (893, 0.0),
 (894, 0.0),
 (895, 0.0),
 (896, 0.0),
 (897, 0.0),
 (898, 0.0),
 (901, 0.0),
 (902, 0.0),
 (903, 0.0),
 (905, 0.0),
 (906, 0.0),
 (907, 0.0),
 (908, 0.0),
 (910, 0.0),
 (911, 0.0),
 (912, 0.0),
 (913, 0.0),
 (914, 0.0),
 (915, 0.0),
 (916, 0.0),
 (917, 0.0),
 (918, 0.0),
 (919, 0.0),
 (920, 0.0),
 (922, 0.0),
 (923, 0.0),
 (924, 0.0),
 (925, 0.0),
 (926, 0.0),
 (927, 0.0),
 (928, 0.0),
 (929, 0.0),
 (930, 0.0),
 (931, 0.0),
 (932, 0.0),
 (933, 0.0),
 (934, 0.0),
 (935, 0.0),
 (936, 0.0),
 (937, 0.0),
 (938, 0.0),
 (939, 0.0),
 (941, 0.0),
 (942, 0.0),
 (943, 0.0),
 (944, 0.0),
 ...]

In [34]:
sorted_indices = [i[0] for i in sortedscore[1:]]
sorted_values = [i[1] for i in sortedscore[1:]]
sorted_values

[0.5773502691896258,
 0.5669467095138407,
 0.5303300858899106,
 0.5303300858899106,
 0.5303300858899106,
 0.5303300858899106,
 0.5303300858899106,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.45226701686664544,
 0.4472135954999579,
 0.4472135954999579,
 0.4472135954999579,
 0.4472135954999579,
 0.4472135954999579,
 0.4472135954999579,
 0.4472135954999579,
 0.4472135954999579,
 0.4330127018922194,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.4082482904638631,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.3779644730092272,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.35355339059327373,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.31622776601683794,
 0.30151134457776363,
 0.30151134457776363,
 0.30151134457776363,
 0.30151134457776363,
 0.30151134457776363,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2886751345948129,
 0.2773500981126146,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.22360679774997896,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.20412414523193154,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.15811388300841897,
 0.15811388300841897,
 0.15811388300841897,
 0.15811388300841897,
 0.15075567228888181,
 0.14433756729740646,
 0.14433756729740646,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 ...]

In [35]:
result = df.iloc[sorted_indices]
result

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day,cleantitle
410,889066,Trading Options Basics,https://www.udemy.com/trading-options-basics/,True,200,8,0,8,Beginner Level,1.5 hours,2016-07-01T03:13:22Z,Business Finance,1600,2016-07-01,03:13:22Z,2016,7,1,Trading Options Basics
43,627540,Options Trading - How to Win with Weekly Options,https://www.udemy.com/work-from-home-setup-you...,True,115,7489,1190,25,Intermediate Level,1 hour,2015-10-22T21:54:28Z,Business Finance,861235,2015-10-22,21:54:28Z,2015,10,22,Options Trading Win Weekly Options
96,474928,Intermediate Options trading concepts for Stoc...,https://www.udemy.com/intermediate-options-tra...,True,40,2000,30,9,All Levels,1 hour,2015-04-13T20:28:04Z,Business Finance,80000,2015-04-13,20:28:04Z,2015,4,13,Intermediate Options trading concepts Stocks O...
138,1243448,Forex Trading with Fixed 'Risk through Options...,https://www.udemy.com/forexoptions/,True,200,611,4,26,Beginner Level,1 hour,2017-06-07T17:15:07Z,Business Finance,122200,2017-06-07,17:15:07Z,2017,6,7,Forex Trading Fixed Risk Options Trading
195,919906,Trading Options For Consistent Returns: Option...,https://www.udemy.com/trading-options-for-income/,False,0,4077,281,20,Beginner Level,1.5 hours,2016-08-18T21:57:04Z,Business Finance,0,2016-08-18,21:57:04Z,2016,8,18,Trading Options Consistent Returns Options Basics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3678,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,True,100,1040,14,21,All Levels,2 hours,2016-06-14T17:36:46Z,Web Development,104000,2016-06-14,17:36:46Z,2016,6,14,Learn jQuery Scratch Master JavaScript library
3679,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,True,25,306,3,42,Beginner Level,3.5 hours,2017-03-10T22:24:30Z,Web Development,7650,2017-03-10,22:24:30Z,2017,3,10,Design WordPress Website Coding
3680,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5 hours,2015-12-30T16:41:42Z,Web Development,20520,2015-12-30,16:41:42Z,2015,12,30,Learn Build Polymer
3681,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,True,50,300,31,38,All Levels,3 hours,2016-08-11T19:06:15Z,Web Development,15000,2016-08-11,19:06:15Z,2016,8,11,CSS Animations Create Amazing Effects Website
3682,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,True,45,901,36,20,Beginner Level,2 hours,2014-09-28T19:51:11Z,Web Development,40545,2014-09-28,19:51:11Z,2014,9,28,MODX CMS Build Websites Beginners Guide

In [36]:
result['similaritscore'] = np.array(sorted_values)
result

C:\Users\sohan\AppData\Local\Temp\ipykernel_14576\2393989520.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['similaritscore'] = np.array(sorted_values)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day,cleantitle,similaritscore
410,889066,Trading Options Basics,https://www.udemy.com/trading-options-basics/,True,200,8,0,8,Beginner Level,1.5 hours,2016-07-01T03:13:22Z,Business Finance,1600,2016-07-01,03:13:22Z,2016,7,1,Trading Options Basics,0.577350
43,627540,Options Trading - How to Win with Weekly Options,https://www.udemy.com/work-from-home-setup-you...,True,115,7489,1190,25,Intermediate Level,1 hour,2015-10-22T21:54:28Z,Business Finance,861235,2015-10-22,21:54:28Z,2015,10,22,Options Trading Win Weekly Options,0.566947
96,474928,Intermediate Options trading concepts for Stoc...,https://www.udemy.com/intermediate-options-tra...,True,40,2000,30,9,All Levels,1 hour,2015-04-13T20:28:04Z,Business Finance,80000,2015-04-13,20:28:04Z,2015,4,13,Intermediate Options trading concepts Stocks O...,0.530330
138,1243448,Forex Trading with Fixed 'Risk through Options...,https://www.udemy.com/forexoptions/,True,200,611,4,26,Beginner Level,1 hour,2017-06-07T17:15:07Z,Business Finance,122200,2017-06-07,17:15:07Z,2017,6,7,Forex Trading Fixed Risk Options Trading,0.530330
195,919906,Trading Options For Consistent Returns: Option...,https://www.udemy.com/trading-options-for-income/,False,0,4077,281,20,Beginner Level,1.5 hours,2016-08-18T21:57:04Z,Business Finance,0,2016-08-18,21:57:04Z,2016,8,18,Trading Options Consistent Returns Options Basics,0.530330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3678,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,True,100,1040,14,21,All Levels,2 hours,2016-06-14T17:36:46Z,Web Development,104000,2016-06-14,17:36:46Z,2016,6,14,Learn jQuery Scratch Master JavaScript library,0.000000
3679,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,True,25,306,3,42,Beginner Level,3.5 hours,2017-03-10T22:24:30Z,Web Development,7650,2017-03-10,22:24:30Z,2017,3,10,Design WordPress Website Coding,0.000000
3680,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5 hours,2015-12-30T16:41:42Z,Web Development,20520,2015-12-30,16:41:42Z,2015,12,30,Learn Build Polymer,0.000000
3681,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,True,50,300,31,38,All Levels,3 hours,2016-08-11T19:06:15Z,Web Development,15000,2016-08-11,19:06:15Z,2016,8,11,CSS Animations Create Amazing Effects Website,0.000000
3682,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,True,45,901,36,20,Beginner Level,2 hours,2014-09-28T19:51:11Z,Web Development,40545,2014-09-28,19:51:11Z,2014,9,28,MODX CMS Build Websites Beginners Guide,0.000000

In [42]:
final_df = result[['cleantitle','similaritscore']]
final_df

                                             cleantitle  similaritscore
410                              Trading Options Basics        0.577350
43                  Options Trading  Win Weekly Options        0.566947
96    Intermediate Options trading concepts Stocks O...        0.530330
138            Forex Trading Fixed Risk Options Trading        0.530330
195   Trading Options Consistent Returns Options Basics        0.530330
...                                                 ...             ...
3678    Learn jQuery Scratch  Master JavaScript library        0.000000
3679                    Design WordPress Website Coding        0.000000
3680                                Learn Build Polymer        0.000000
3681      CSS Animations Create Amazing Effects Website        0.000000
3682            MODX CMS Build Websites Beginners Guide        0.000000

[3682 rows x 2 columns]

In [81]:
def recommend(title, n=10):
    courseindex = pd.Series(df.index, index=df['course_title']).drop_duplicates()
    index = courseindex[title]
    scores = list(enumerate(cosine_similarity[index]))
    sortedscore = sorted(scores,key = lambda x:x[1],reverse=True)
    sorted_indices = [i[0] for i in sortedscore[1:]]
    sorted_values = [i[1] for i in sortedscore[1:]]
    result = df.iloc[sorted_indices]
    result['similarityscore'] = np.array(sorted_values)
    final_recommended_courses = result[['course_title', 'similarityscore', 'url', 'price', 'num_subscribers']]
    return final_recommended_courses.head(n)

In [82]:
recommend('Forex Trading A-Z™ - With LIVE Examples of Forex Trading', 10)

C:\Users\sohan\AppData\Local\Temp\ipykernel_14576\3744669625.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['similarityscore'] = np.array(sorted_values)

,course_title,similarityscore,url,price,num_subscribers
20,Winning Forex Trading with Live Forex Trading ...,0.909091,https://www.udemy.com/forexmacross/,200,809
471,Forex Trading,0.852803,https://www.udemy.com/how-to-trade-forex/,95,136
398,Forex Trading: Comprehensive & Concise Forex T...,0.727273,https://www.udemy.com/forex-trading-comprehens...,160,2379
709,Forex Trading - Learn An Effective Forex Tradi...,0.727273,https://www.udemy.com/forex-trading-strategy-t...,95,223
997,Forex Harmonic Trading- With Multiple Forex Ch...,0.703526,https://www.udemy.com/forex-harmonic-trading-w...,135,313
108,Fundamentals of Forex Trading,0.696311,https://www.udemy.com/fundamentals-of-forex-tr...,0,17160
477,Forex Trading Profitably,0.696311,https://www.udemy.com/learn-how-to-make-1000s-...,20,512
745,Forex trading made simple,0.696311,https://www.udemy.com/forex-mentor-online-school/,100,45
777,Forex Elite Trading,0.696311,https://www.udemy.com/elite-forex-trading-syst...,85,623
823,Forex Trading Plan,0.696311,https://www.udemy.com/forex-trading-plan/,50,21

In [85]:
list(df['cleantitle'])

['Ultimate Investment Banking Course',
 'Complete GST Course  Certification  Grow Practice',
 'Financial Modeling Business Analysts Consultants',
 'Beginner Pro  Financial Analysis Excel 2017',
 'Maximize Profits Trading Options',
 'Trading Penny Stocks Guide Levels 2017',
 'Investing Trading Beginners Mastering Price Charts',
 'Trading Stock Chart Patterns Immediate Explosive Gains',
 'Options Trading 3  Advanced Stock Profit Success Method',
 'Investment Strategy Need Retirement',
 'Forex Trading Secrets Pros Amazons AWS',
 'Trading Options Money Flow',
 'Financial Management Risk Return Securities',
 'Forex Trading Course Work Smarter Harder Proven Results',
 'Python Algo Trading Sentiment Trading News',
 'Short Selling Learn Sell Stocks Fall',
 'Basic Technical Analysis Learn structure market',
 'Complete Chart Pattern Trading Course Proven Approach',
 '7 Deadly Mistakes Investing Slash Profits',
 'Financial Statements Easy',
 'Winning Forex Trading Live Forex Trading Examples',
 'Forex Traders  Create Trading Robot Coding',
 'Create Business Home Trading Stocks Today 2017',
 'Introduction Accounting  Mastering Financial Statements',
 'Complete Ethereum Course 01 Ether Wallet',
 'Beginner Pro PowerPoint Complete PowerPoint Training',
 'Investing 101 Complete Online Investing Course',
 'Create Hedge Fund Trade Stocks Like Fund Manager',
 'Learn MQL5 Build 8Currency Hedging Robot MetaTrader 5',
 'Forex Trading Complete Guide Started Like Pro',
 'Python Algo Stock Trading Automate Trading',
 'Forex Robot Incredible ROI Robot Included',
 'Complete Bitcoin Course 001 Bitcoin Wallet',
 'Mastering High Probability Iron Condor Options Trading',
 'Complete Short Course Ethereum',
 'Options Trading Stocks Proven Toolbox Financial Success',
 'Forex Trading AZ  LIVE Examples Forex Trading',
 'Introduction Finance Accounting Modeling Valuation',
 'Beginner Pro Excel Financial Modeling Valuation',
 'Complete Investment Banking Course 2017',
 'Complete Financial Analyst Course 2017',
 'Python Finance Investment Fundamentals  Data Analytics',
 'Financial Modeling Startups  Small Businesses',
 'Options Trading  Win Weekly Options',
 'Black Algo Trading Build Trading Robot',
 'Accounting  Financial Statement Analysis Complete Training',
 'Cryptocurrency Trading Complete Guide Trading Altcoins',
 'Forex Robots Expect Earn 175 PA Forex Robot Included',
 'Steps Trading  Live Trading  Real Account',
 'Option Trading Rookies Understand Options Completely',
 'Learned Stock Trading and Too',
 'Learn Trade Profit Find Trade Winning Stocks',
 'Trading Inside Bars  Master 1 Easy Pattern Successful',
 'Fundamentals Financial Planning',
 'Options Trading  Calendar Spread Course Trader',
 'Dividend Investing Build Portfolio Better Future',
 'Learn Accounting Understand Business',
 'Consistently Win Trading Stocks 30 Days',
 'Beginners Guide Quantopian Futures API',
 'Buy Cheap Options  Options Trading Pricing Model',
 'Excel Crash Course Master Excel Financial Analysis',
 'Comprehensive Guide Financial Markets Investing Trading',
 'Stock Trading Ninja Complete System Trading Success',
 'Hedge Mutual Fund Careers Complete Guide',
 'Algorithmic Trading Forex Create Forex Robot',
 'Power Modeling Bootcamp Advanced Excel 10 Days',
 'Options Trading Basics 3Course Bundle',
 'Win 97 Options Trades',
 'Consistent Returns Trading Options',
 'Forex Strategies Kelly Criterion Larry Williams more',
 'Elite Trend Trader Learn Trade Stocks Options  Forex',
 'Options Trading Introduction Day Trade Stock Options',
 'Perfect Options Trading Strategy System  Unique',
 'Forex Trading  Learn Trade Forex Like Banks',
 'Learn Trade ProfitTrading Japanese Candlesticks',
 'Powerful Options Spread Trading Ratio Spread',
 'Finance Job You Explanation 14 Finance Roles',
 'Blueprint Successful Stock Trading',
 'Trading Beginners  Intermediate Level',
 'Start Trading Stocks Technical Analysis',
 'Learn Set Incubator Hedge Fund  StepbyStep',
 'VPS Forex Trading  Protect Forex Robots',
 'Introduction Accounting Language Business',
 'Basic Excel Basic Bookkeeping Accounting',
 'The Greeks Understand Options',
 'Trading Options Consistent Returns Calendar Spreads',
 'Create Personal Budget',
 'Complete Value Investing Course Proven Approach',
 'FOREX Trading Price Action',
 'Emini ES Futures  Advanced Non Directional Options Trading',
 'Forex Trading  Advanced Fundamental Analysis',
 'Invest Tiny Capital Stocks ',
 'Learn Successfully Trade Stocks 5 Simple Steps',
 'Test knowledge Basics Accounting',
 'Forex MetaTrader 4 Master MT4 Like Pro Forex Trader',
 'Test Knowledge Cost Accounting',
 'Intermediate Options trading concepts Stocks Options',
 'Options Trading 101 Basics',
 'Practical Accounts APP Overview',
 'Bitcoin Profits Beginners',
 'Trend Traders Club Find Trade Fast Moving Trends',
 'Financial Statements Basics',
 'High performance Stock Trading key Options techniques',
 'Introduction Financial Statement Analysis',
 'Basics Economics College Level',
 'Stock Market Investing Beginners',
 'Accounting Beginners  Learn Basics 1 Hour',
 'Straddle Options Trading  Profit Market Direction',
 'Fundamentals Forex Trading',
 'Binary Options Trading Strategies 90 Accuracy Signals',
 'Website Investing 101  Buying  Selling Online Businesses',
 'Practical Accounts  Bookkeeping Automated Overview',
 'Live Account  ETF Trading System  Hacking Stock Market',
 'Stock Market Leverage Start Trading Options Wisely',
 'Stock Market Foundations',
 'Crash Course Working Capital Management',
 'Advanced Accounting Complete Study  CMA  CFA  CS',
 '61 Profit 1 Month  Crush Forex Trading Paradigm',
 'create routine Trading',
 'Forex Trading Secrets MT4 Robot EA inside coding',
 'Forex SOS Course Trading Tweaks Working Forex Strategy',
 'Introduction Financial Modeling',
 'Quantitative Aptitude Banking  Competitive Examinations',
 'Option Spreads Credit Spreads Bundle',
 'B Com Accountancy Paper ECO 02 IGNOU',
 'FOREX TRADING  Learn quick  profitable way  support',
 'Auditing Basics Professional Course Level',
 'Stock market Investing Encyclopedia invest stocks',
 'Learn basics preparing accounting statements',
 'Elliott Wave Forex Trading Elliott Wave Theory',
 'Corporate Finance  Brief Introduction',
 'Excel functions analyze visualize data',
 'Building Financial Statements Excel',
 'Transfer Pricing Complete Analysis',
 'Accounting Hired Work Experience',
 'Forex Trading Beginners  Basics',
 'Basic Bookkeeping Hacks',
 'Complete Trading Plan Course Stocks  Forex 10 Hours',
 'Forex Trading Fixed Risk Options Trading',
 'Intro Investment Banking MA IPO Modeling  Free Book',
 'Pick Right Penny Stocks Invest 2017',
 '10 Trading Ideas Equities Market',
 'Intro Financial Modeling',
 'Shark Accounting  Building Business Numbers',
 'Forex Trading TRADE TODAY',
 'Accounting 60 Minutes  Brief Introduction',
 'SAP FICO Beginners  Guide SAP Financial Accounts',
 'Learn double Forex Trading Account trade',
 'Accounting Superpowers Learn Accounts Understand Business',
 'Python Algo Trading FX Trading Oanda',
 'Save Taxes',
 'Financial Model Basics Build model start finish',
 'Option Trading Rookies Covered Option Strategy',
 'EFT Stock Options Trading Success  Making Better Trades',
 'Learn Trade Stock Market Blowing Profits',
 'Credit Repair Publication Amazon Live LIFE',
 'Fundamentals Accounting',
 'RSI Options Trading  Technical Analysis 3 Course Bundle',
 'Basics Mutual Funds  CMA  CS  CFA Exams',
 'Accounting 101 read Accounting Balance Sheet',
 'Stock Options Day Trading Mindset Success',
 'Introduction bookkeeping Accounting',
 'Learn Trade News',
 'Value Investing Taught Superinvestors',
 'Trading  Independent Investor Course',
 'Acquired Learn Head Acquisitions eBay',
 'Stock Market investment Practical Accounting',
 'remove Risk Penny Stocks  Options Trading',
 'Accounting Basics 66 Minutes absolutely beginners',
 'Tax Accounting Difficult Topic Easy Understand',
 'Analysis Company Financial Statements',
 'Forex Trading Like Banks  Step Step Live Examples',
 'Fundamentals Investing',
 'Bank Financial Management Comprehensive Study',
 'Learn Trade Forex Stocks Beginner Advanced',
 'Master Technical Analysis Chart reading skills Bundle',
 'Naked Options Trade Covered  Poor Man Covered',
 'Ultimate Guide Dividend  Dividend Growth Investing',
 'Charting Beginners 101 Technical Analysis Demystified',
 'Build DCF Valuation Model',
 'Introductory Financial Accounting',
 'Introduction Cryptocurrencies Blockchain',
 'Trade Pullback Candlestick Strategy  Consistent Pips',
 'Accounting Standards Basics Professional Course Level',
 'Use Magic Multiple Moving Average Forex Trading system',
 'QuickBooks 2015 Training Newbies',
 'TRADING PSYCHOLOGY Trading Mindset Mastery',
 'Option Trading Adjust DeltaNeutral Strangles',
 'Profitable binary option trading strategy',
 'Tax Strategy Financial Planning Beginners',
 'Accounting 2 Simplified',
 'Project Funding Modelling for Professionals',
 'Investing Consistently Beat Stock Market',
 'Bookkeeping Basics Understand Fundamentals',
 'Leasing  Comprehensive Study Professional Course Level',
 'Trading Options Consistent Returns Options Basics',
 'TechniTrader Leading Hybrid Indicator Trading',
 'Financial modeling Build DCF equity valuation model',
 'CryptoArbitrager Bitcoin Trading Robot no mining',
 'Accounting Easy for Beginners',
 'Non Directional Weekly Options Trading System  ETF  Emini',
 'Complete Position Trading Course Position Trading Stock',
 'Master Iron Condors  Double credit half risk',
 'Basics investing Mutual Funds',
 'Value Investing Approach Stock Market',
 'Learn INVEST huge profits big trading',
 'Fund Million Dollar Idea Equity Debt Unfund',
 'Mastering Candlestick Charting  High Probability Trading',
 'Binary Options Course  Level 2',
 'Stock Technical Analysis R',
 'know VIX Index aka The Fear Index',
 'Apply finance concepts smart project management',
 'Introduction Futures Trading Live Trade Demonstration',
 'Crowdfunding Win',
 'Comprehensive Forex Mastery Program',
 'Preparation Consolidated Financial Statements Basic',
 'Succeed Bonds Know Start',
 'Learn Trade Profit Profitable Trading Rules',
 'Succeed Lotto Know Start',
 'CFA Corporate Finance Level 2',
 'Pin Bars Powerful Forex Trading Signal',
 'Stock Options Trades Interactive Brokers',
 'Introduction Options  Strategies Consistent Profits',
 'Risk Forex Transactions   CS  CFA exams',
 'Basics Business Statistics College Level',
 'Trading Seasonal Price Patterns Stocks Futures  Forex',
 'Interpreting Financial Statements',
 'Introduction Bookkeeping Accounting',
 'CREDIT SPREAD SURGERY  Bear Bull Mastery',
 'Investment Banking Land Job Wall Street',
 'Learn Invest Index Funds ETFs 7 Easy Steps',
 'Financial modeling Build multiples valuation model',
 'Trade Recap  Real Look Futures Options Markets',
 'Advanced Stock Options Equity Investors',
 'Trading Binary Options Fun Profit',
 'CFA Fast Track career Finance',
 'Profitable Forex Trader',
 'Excel Dashboard  Interactive Excel Dashboard Charts',
 'Accounting 101 Learn Business Finance Forecasting 60mins',
 'Securities Trade Lifecycle',
 'Double Forex Account MAGIC trading robot',
 'Technical Analysis 101 Profit Market Crashes',
 'Advanced Accounting Investment Banking',
 'Investing Stocks 10 Simple Rules',
 'Venture Capital Matters You',
 'Cash Flow Valuation Develop Financial Literacy',
 'DirectionIndepend Trading  Elite Forex Traders Strategy',
 'Financial Analyst Scratch',
 'Steps Trading Forexmarkets  Technical Analysis',
 'Financial analysis Compare performance companies',
 'Forex Beginners Easy Forex Trading Beginners',
 'Investment Crowdfunding 101 aka Equity Crowdfunding',
 'Read financial statements like pro',
 '10 Numbers Business Owner Know',
 'Learn Trade Gold 2017',
 'IAS 18  Revenue',
 'Forex Trading High ROI Forex Trading End Day Course',
 'Fundraise Simplified Way Crowdfunding Blueprint',
 'Fundamentals Accounting Business Owners',
 'Practical Financial Statement Analysis',
 'Forex Management  Detailed Study  CS  CFA Exams',
 'Financial Statement Review 101 Find Errors',
 'Professional Risk Manager PRM Certification Level 1',
 'International Tax  Tax boundaries',
 'Complete Financial Statement Analysis Course',
 'Advanced Excel functions',
 'Penny Stocks Value  Chart Pattern Trading 2 Course Bundle',
 'Candlestick Analysis Professional Traders',
 'Build Career Forex Trading Learn Fundamental Analysis',
 'Financial Modeling Build Complete DCF Valuation Model',
 'Handson Financial Modeling With 6 Excel Templates',
 'CAIIB Advanced Bank Management Part I',
 'Stock Market investmentNon financial fundamental analysis',
 'Learn Play CashFlow Game',
 'Basics Business Finance',
 'Accounting Easy 2',
 'Bitcoin el futuro del dinero hoy',
 'Aprende invertir practicando',
 'Trading con retrocesos de Fibonacci',
 'Mit Finanzwissen zu besserem Unternehmertum',
 'Como hacer empresa en 10 sesiones prcticas',
 '    ',
 '',
 'Curso de Trading prctico basado en casos reales',
 'Curso Avanzado de Trading',
 ' ',
 'MQL4 Tutorial Golden Goose',
 'Anlise de Concesso de Crdito',
 'Technical Analysis Elliott Wave Theory',
 'Basics Volume Analysis',
 'Crash Course Cost Capital Capital Structuring',
 'Business Accounting Easy',
 'Build DCF Model Scratch',
 'Multiply returns Value Investinghttpswwwudemycommultiplyyourreturnsusingvalueinvestingtrue2019421963All Levels45 hours20150723T000833Z 874284Weekly Forex Analysis Baraq FX',
 'Technical Analysis  practical approach trade entry',
 'Mastering Technical Analysis  Maximizing Trading Profits',
 'Complete Guide Professional Trading Elliott Wave',
 'Complete Guide Trader Forex Market',
 'Stock Market Beginners  Complete Starter Toolkit',
 'Beginners Binary Options Course',
 'Technical Analysis 101 Secrets Trading Revealed',
 'Forex Whats Trend Strong Reliable',
 'Volatility Trading Analysis R',
 'Profit Stock Market Volatility',
 'Awaken Accountant  Master Accounting Basics',
 'PAY TRADE',
 'Situational Trading Proven Option Strategy Scenario',
 'Portfolio Management  CS  CFA exams',
 'Algorithmic Trading MATLAB WFAToolbox App GUI Finance',
 'Finding Unlimited Investors',
 'Bookkeeping Easy',
 'BITCOIN VISUALLY I',
 'Learn Master Basics Finance',
 'FOREX  LearnTo Trade Improved  Advanced  Patterns',
 'Mastering Market  Technical Analysis  Candlestick',
 'Mastering Countertrend Trading  High Profit Trading Pattern',
 'Exam 1 Review  Managerial Accounting U H',
 ' Integrated Approach Fundamentals Accounting',
 'grips CFA calculator',
 'Financial Model FundamentalsLearn Essential Skills',
 'Forex Economic News Trading',
 'Analyze Real Estate Investments  Financial Modeling',
 'Forex Beginners  Guide Currency Trading',
 'Raise Credit Score 800 More',
 'Financial Management Budgeting Techniques',
 'Forex Killing Divergence  trade precision',
 'Working Capital Management  CFA  CPA Exams',
 'Risk Analysis  Capital Budgeting  CS  CFA exams',
 'Corporate Finance 101 Financial Statement Analysis  Ratios',
 'Mastering Futures Options Beginners  5 Plays',
 'Professional Options Trading Simplified',
 'Advanced Options Concepts  Probability Greeks Simulation',
 'Accounting Basics  Complete Study',
 'Case Studies Macro Economics',
 'Forex Strategy win consistently',
 'Understand Banks  Financial Markets',
 'Stock Technical Analysis Python',
 'Accountant scratch',
 'invest Gold',
 'Automate Finances',
 'MBA Accounting Finance ManagersPaper MS04 IGNOU',
 'Accounting Easy Quick Guide Financial Accounting',
 'FuturesCommodity Training Basics',
 'Cost Accounting Marginal Costing Theory Practice',
 'Big Volatility Short Best Trade Wall Street',
 'Master Finance Hours',
 'Learn Options Futures Hedging Options Stocks',
 'Option selling trading income source Beginners friendly',
 'Introduction Value Growth Investing',
 'Forex Trader  Forex trading like professional',
 'Hedge Fund Trading System',
 'Bulletproof Personal Finance Expert Asset Allocation',
 'Financial Accounting Complete Introductory Crash Course',
 'Learn Trading Options real wallstreet trader',
 'Forex Rate Why fluctuates for  CMA  CS  CFA Exams',
 'Build Massive Stock Portfolio Zero',
 'Introductory Forex Trading Course',
 'Budgeting Hacks Build Wealth',
 'Accounting Finance Bankers  Comprehensive Study',
 'Forex Prep Academy BeginnersReal trades',
 'Accounting Deferred Taxes Professional Course Level',
 'TRADING TRUTHS',
 'Binary Institute  Introductory Course Binary Options',
 'Forex Trading vs Option Trading',
 'Invest Stocks  Billionaire Investing Tips',
 'Value Investing Beginners',
 'TRADING TACTICS',
 'MQL4 Tutorial Bootcamp  Trading Robot Coding Metatrader4',
 'Ultimate Retirement Build Dynamic Retirement Plan',
 'build solid foundation trading options',
 'Forex Scam Avoid scam today',
 'Cost Accounting Crash Course',
 'Option Trading Rookies Basic Option Strategies',
 'Business Analysis Working Use Cases',
 'Learn Raise Funds Need Crowdfunding',
 'Business finances',
 'Financial Accounting  Brief Introduction',
 'Trading Economic Indicators  Complete Trading System',
 'Foundation Options Trading Investing',
 'Option Trading  Earn Cant Predict Market',
 'Financial Analyst Skills Training FAST course 2017',
 'Covered Calls  Powerful Income Strategy Stock Traders',
 'Accounting 1 Simplified',
 'Value Investing White People Money',
 'Start Investing Simple Easy',
 'Basics Commerce Complete Study',
 'Passive Investing Blueprint  Build Wealth Passively',
 '7 Steps Introduction Trading',
 'Forex  Elliott Wave Theory Fibonacci',
 'Actuarial Profession Basic Sciences Principles',
 'Investing stocks Avoid stock market loss',
 'QuickBooks Online Complete Guide  Certification tips',
 'Build Financial Models  Value Companies Easy Way',
 'Adventure Capital pay debt',
 'Chart Patterns Trading Demystified',
 'Financial Planning  Analysis Building Companys Budget',
 'Simple things know start FOREX OFFER',
 'Practical Finance',
 'Forex Trading Comprehensive  Concise Forex Trading Course',
 'Leaps Options Trading System  Diagonal Leaps Options Spread',
 'Finance  Ratios Analysis  Interpretations',
 'Forex Trading  Learn Trade Scratch',
 'Technical Analysis tools Stocks Options trading',
 'Quantitative Trading Analysis R',
 'Penny Stocks King 2 Trade Penny Stocks 6 Hours',
 'Started Penny Stocks Step Step Guide Trading',
 'CPA 101 Master Affiliate Marketing Time',
 'Corporate Internal Controls Fraud Controls',
 'Forex trading tactics work',
 'Professional Risk Manager PRM Certification Level 2',
 'Trading Options Basics',
 'Practical Trading Financial Futures  Options Markets',
 'Bookkeeping simple',
 'Visual Learning Basic Accounting Course',
 'ChalkTalk Financial Accounting',
 '7 fundamentals Successful Cashflow Management',
 'trade options',
 'Coaching CourseInvestment Analysis clients',
 'Harnessing Power Growth Stocks',
 'Investment Banking Recruitment Series',
 'Business Banking 101',
 'CFA Level Workshop 2 Financial Reporting  Analysis',
 'Breakout Patterns Workshop Pattern Trader',
 'Asset Protection Offshore Companies',
 'Credit EIN Thats Linked SSN',
 'Financial Translation',
 'Pick Stocks',
 'Binary Beginners Mastery Strategy',
 'Accounting 101Master Class Understanding Business',
 'HighFrequency Trading  Dark Pools',
 'Crowdfund',
 'Financial Statement Fundamentals Small Biz  Investors',
 'Master Stock Market practice',
 'Introduction Trade Theory Technical Analysis Stocks',
 'Forex Trading Beginners Technical Trading',
 'IAS 12  Accounting Income Taxes Basics',
 'Surpassing Kickstarter Goals',
 'Simple Linear Regression Analysis  Complete Course ',
 'Forex Learn Trade Forex FX Consistently',
 'Trading HighROI Trading',
 'Fundraising 101',
 'Professional Bookkeeping  Accounting 2  Bank Daybook',
 'Filing Companies House UK',
 'Build Grow Protect Assets StepbyStep Guide',
 'Advantages ETF Options Index Options Trading',
 'Learn Trade Forex  Beginner Professional',
 'Investing Stocks Big Gains Fundamental Investing',

In [69]:
df.to_csv('UdemyCleanedTitle.csv',index = None)

In [86]:
new = pd.read_csv('UdemyCleanedTitle.csv')
new

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day,cleantitle
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance,429400,2017-01-18,20:58:58Z,2017,1,18,Ultimate Investment Banking Course
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance,209400,2017-03-09,16:34:20Z,2017,3,9,Complete GST Course Certification Grow Practice
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance,97830,2016-12-19,19:26:30Z,2016,12,19,Financial Modeling Business Analysts Consultants
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance,232845,2017-05-30,20:07:24Z,2017,5,30,Beginner Pro Financial Analysis Excel 2017
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance,255200,2016-12-13,14:57:18Z,2016,12,13,Maximize Profits Trading Options
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3678,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,True,100,1040,14,21,All Levels,2 hours,2016-06-14T17:36:46Z,Web Development,104000,2016-06-14,17:36:46Z,2016,6,14,Learn jQuery Scratch Master JavaScript library
3679,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,True,25,306,3,42,Beginner Level,3.5 hours,2017-03-10T22:24:30Z,Web Development,7650,2017-03-10,22:24:30Z,2017,3,10,Design WordPress Website Coding
3680,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5 hours,2015-12-30T16:41:42Z,Web Development,20520,2015-12-30,16:41:42Z,2015,12,30,Learn Build Polymer
3681,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,True,50,300,31,38,All Levels,3 hours,2016-08-11T19:06:15Z,Web Development,15000,2016-08-11,19:06:15Z,2016,8,11,CSS Animations Create Amazing Effects Website
3682,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,True,45,901,36,20,Beginner Level,2 hours,2014-09-28T19:51:11Z,Web Development,40545,2014-09-28,19:51:11Z,2014,9,28,MODX CMS Build Websites Beginners Guide

In [87]:
list(new['course_title'])

['Ultimate Investment Banking Course',
 'Complete GST Course & Certification - Grow Your CA Practice',
 'Financial Modeling for Business Analysts and Consultants',
 'Beginner to Pro - Financial Analysis in Excel 2017',
 'How To Maximize Your Profits Trading Options',
 'Trading Penny Stocks: A Guide for All Levels In 2017',
 'Investing And Trading For Beginners: Mastering Price Charts',
 'Trading Stock Chart Patterns For Immediate, Explosive Gains',
 'Options Trading 3 : Advanced Stock Profit and Success Method',
 'The Only Investment Strategy You Need For Your Retirement',
 "Forex Trading Secrets of the Pros With Amazon's AWS",
 'Trading Options With Money Flow',
 'Financial Management Risk and Return For Securities',
 'Forex Trading Course: Work Smarter Not Harder Proven Results',
 'Python Algo Trading: Sentiment Trading with News',
 'Short Selling: Learn To Sell Stocks Before The Fall',
 'Basic Technical Analysis: Learn the structure of the market',
 'The Complete Chart Pattern Trading Course: A Proven Approach',
 '7 Deadly Mistakes of Investing that Will Slash Your Profits!',
 'Financial Statements Made Easy',
 'Winning Forex Trading with Live Forex Trading Examples',
 'Forex Traders - Create Your First Trading Robot. No Coding!',
 'Create A Business From Home Trading Stocks Today In 2017',
 'Introduction to Accounting : Mastering Financial Statements',
 'The Complete Ethereum Course: Get .01 Ether In Your Wallet',
 'Beginner to Pro in PowerPoint: Complete PowerPoint Training',
 'Investing 101: The Complete Online Investing Course',
 'Create Your Own Hedge Fund: Trade Stocks Like A Fund Manager',
 'Learn MQL5: Build an 8-Currency Hedging Robot (MetaTrader 5)',
 'Forex Trading: Your Complete Guide to Get Started Like a Pro',
 'Python Algo Stock Trading: Automate Your Trading!',
 'THE Forex Robot: Incredible ROI (Robot Included)',
 'The Complete Bitcoin Course: Get .001 Bitcoin In Your Wallet',
 'Mastering High Probability Iron Condor Options Trading',
 'The Complete Short Course on Ethereum',
 'Options Trading Stocks: Proven Toolbox For Financial Success',
 'Forex Trading A-Z™ - With LIVE Examples of Forex Trading',
 'Introduction to Finance, Accounting, Modeling and Valuation',
 'Beginner to Pro in Excel: Financial Modeling and Valuation',
 'The Complete Investment Banking Course 2017',
 'The Complete Financial Analyst Course 2017',
 'Python for Finance: Investment Fundamentals & Data Analytics',
 'Financial Modeling for Startups & Small Businesses',
 'Options Trading - How to Win with Weekly Options',
 'Black Algo Trading: Build Your Trading Robot',
 'Accounting & Financial Statement Analysis: Complete Training',
 'Cryptocurrency Trading: Complete Guide To Trading Altcoins',
 'Forex Robots: Expect To Earn 175% P.A. Forex Robot Included!',
 'Three Steps Trading - Live Trading - Real Account',
 'Option Trading for Rookies:  Understand Options Completely',
 'How I Learned Stock Trading (and How You Can Too)',
 'Learn to Trade for Profit: Find and Trade Winning Stocks',
 'Trading Inside Bars - Master 1 Easy Pattern To Be Successful',
 'Four Fundamentals of Financial Planning',
 'Options Trading - Calendar Spread Course for Every Trader',
 'Dividend Investing: Build Your Portfolio for a Better Future',
 'Learn Accounting. Understand Business.',
 'How to Consistently Win Trading Stocks in 30 Days or Less',
 "A Beginner's Guide to Quantopian Futures API",
 'How to Buy Cheap Options - Options Trading Pricing Model',
 'Excel Crash Course: Master Excel for Financial Analysis',
 'Comprehensive Guide to Financial Markets, Investing &Trading',
 'Stock Trading Ninja: Complete System For Trading Success',
 'Hedge and Mutual Fund Careers: The Complete Guide',
 'Algorithmic Trading In Forex: Create Your First Forex Robot!',
 'The Power Modeling Bootcamp: Advanced Excel in 10 Days',
 'Options Trading Basics (3-Course Bundle)',
 'How to Win 97% of Your Options Trades',
 'How I Make Consistent Returns Trading Options',
 'Forex Strategies: Kelly Criterion, Larry Williams and more!',
 'Elite Trend Trader: Learn To Trade Stocks, Options & Forex',
 'Options Trading Introduction: Day Trade Stock Options',
 'The Almost Perfect Options Trading Strategy System - Unique',
 'Forex Trading -  Learn to Trade Forex Like the Banks',
 'Learn to Trade for Profit:Trading with Japanese Candlesticks',
 'The Most Powerful Options Spread Trading Front Ratio Spread',
 'What Finance Job is for You? Explanation of 14 Finance Roles',
 'The Blueprint for Successful Stock Trading',
 'Trading for Beginners - Intermediate Level',
 'Start Trading Stocks Using Technical Analysis!',
 'Learn How to Set Up an Incubator Hedge Fund - Step-by-Step',
 'VPS for Forex Trading - Protect Your Forex Robots',
 'Introduction to Accounting: The Language of Business',
 'Basic Excel for Basic Bookkeeping and Accounting',
 'Using \'The Greeks To Understand Options"',
 'Trading Options For Consistent Returns: Calendar Spreads',
 'How to Create Your Personal Budget',
 'The Complete Value Investing Course: A Proven Approach',
 'FOREX Trading with Price Action',
 'Emini ES Futures - Advanced Non Directional Options Trading',
 'Forex Trading - Advanced Fundamental Analysis',
 'How To Invest With Tiny Capital In Stocks ?',
 'Learn How To Successfully Trade Stocks: In 5 Simple Steps',
 'Test your knowledge in Basics of Accounting',
 'Forex MetaTrader 4: Master MT4 Like A Pro Forex Trader',
 'Test your Knowledge in Cost Accounting',
 'Intermediate Options trading concepts for Stocks and Options',
 'Options Trading 101: The Basics',
 'Practical Accounts APP Overview',
 'Bitcoin Profits for Beginners',
 'Trend Traders Club: How To Find And Trade Fast Moving Trends',
 'Financial Statements Basics',
 'High performance Stock Trading using key Options techniques',
 'Introduction to Financial Statement Analysis',
 'Basics of Economics (College Level)',
 'Stock Market Investing for Beginners',
 'Accounting for Beginners : Learn Basics in under 1 Hour',
 'Straddle Options Trading - Profit in Any Market Direction',
 'Fundamentals of Forex Trading',
 'Binary Options: Trading Strategies, 90% Accuracy and Signals',
 'Website Investing 101 - Buying & Selling Online Businesses',
 'Practical Accounts & Bookkeeping Automated Overview ',
 'Live Account - ETF Trading System - Hacking The Stock Market',
 'Stock Market Leverage: How to Start Trading Options Wisely',
 'Stock Market Foundations',
 'Crash Course on Working Capital Management',
 'Advanced Accounting A Complete Study for CA / CMA / CFA / CS',
 '61% Profit In 1 Month - Crush Your Forex Trading Paradigm',
 'How to create a routine Trading',
 'Forex Trading Secrets |MT4 Robot (EA) inside, no coding',
 'Forex SOS Course: Trading Tweaks And Working Forex Strategy',
 'Introduction to Financial Modeling',
 'Quantitative Aptitude for Banking & Competitive Examinations',
 'Option Spreads and Credit Spreads Bundle',
 'B Com Accountancy I (Paper ECO 02 IGNOU)',
 'FOREX TRADING - Learn in a quick + profitable way + support',
 'Auditing Basics (Professional Course Level)',
 'Stock market Investing Encyclopedia: How to invest in stocks',
 'Learn the basics of preparing accounting statements',
 'Elliott Wave -Forex Trading With The Elliott Wave Theory',
 'Corporate Finance - A Brief Introduction',
 'Excel functions to analyze and visualize data',
 'Building Financial Statements in Excel',
 'Transfer Pricing A Complete Analysis',
 'Accounting: Get Hired Without Work Experience',
 'Forex Trading for Beginners - Basics',
 'Basic Bookkeeping Hacks',
 'Complete Trading Plan Course for Stocks & Forex (10 Hours)',
 'Forex Trading with Fixed \'Risk through Options Trading"',
 'Intro to Investment Banking, M&A, IPO, Modeling + Free Book',
 'How to Pick The Right Penny Stocks To Invest In 2017',
 'Top 10 Trading Ideas in the Equities Market',
 'Intro to Financial Modeling',
 'Shark Accounting - Building a Business by the Numbers!',
 'Forex Trading MAKE YOUR FIRST TRADE TODAY!',
 'Accounting in 60 Minutes - A Brief Introduction',
 'SAP FICO For Beginners - A Guide to SAP Financial Accounts',
 'Learn how to double your Forex Trading Account in one trade',
 'Accounting Superpowers: Learn Accounts, Understand Business!',
 'Python Algo Trading: FX Trading with Oanda',
 'Save on Your Taxes',
 'Financial Model Basics: Build a model from start to finish',
 'Option Trading for Rookies: The Covered Call Option Strategy',
 'EFT for Stock Options Trading Success & Making Better Trades',
 'Learn to Trade the Stock Market without Blowing Your Profits',
 'Get a Credit Repair Publication On Amazon and Live LIFE..',
 'Fundamentals of Accounting',
 'RSI, Options Trading & Technical Analysis (3 Course Bundle)',
 'Basics of Mutual Funds for CA / CMA / CS / CFA Exams',
 'Accounting 101: How to read an Accounting Balance Sheet',
 'Stock Options Day Trading Mindset for Success',
 'Introduction to bookkeeping and Accounting',
 'Learn to Trade The News',
 'Value Investing, Taught by Six Superinvestors',
 'Trading for everyone - The Independent Investor Course I',
 'Get Acquired: Learn From The Head Of Acquisitions For eBay',
 'Stock Market investment: Practical Accounting',
 'How to remove \'Risk from Penny Stocks - Options Trading"',
 'Accounting Basics in 66 Minutes (absolutely for beginners)',
 'Tax Accounting: Difficult Topic, Made Easy to Understand',
 'Analysis of Company Financial Statements',
 'Forex Trading Like Banks – Step by Step with Live Examples',
 'Fundamentals of Investing!',
 'Bank Financial Management A Comprehensive Study',
 'Learn to Trade Forex and Stocks: From Beginner to Advanced',
 'Master \'Technical Analysis and Chart reading skills Bundle"',
 'Naked Put Options Trade Covered Call & Poor Man Covered Call',
 'The Ultimate Guide to Dividend & Dividend Growth Investing',
 'Charting for Beginners 101: Technical Analysis Demystified',
 'Build a DCF Valuation Model',
 'Introductory Financial Accounting',
 'Introduction to Cryptocurrencies and Blockchain',
 'Trade Pullback Candlestick Strategy - Make Consistent Pips',
 'Accounting Standards Basics (Professional Course Level)',
 'Use the Magic Multiple Moving Average Forex Trading system',
 'QuickBooks 2015 Training for Newbies',
 'TRADING PSYCHOLOGY: Trading Mindset Mastery',
 'Option Trading: How to Adjust Delta-Neutral Strangles!',
 'Profitable binary option trading strategy',
 'Tax Strategy: Financial Planning for Beginners',
 'Accounting 2 Simplified for You',
 'Project Funding Modelling (for Professionals)',
 'Investing: How I Consistently Beat The Stock Market',
 'Bookkeeping Basics:  Understand the Fundamentals',
 'Leasing - A Comprehensive Study (Professional Course Level)',
 'Trading Options For Consistent Returns: Options Basics',
 'TechniTrader Leading Hybrid Indicator Trading',
 'Financial modeling: Build a DCF equity valuation model',
 'CryptoArbitrager: Bitcoin Trading Robot (no mining)',
 'Accounting Is Easy (for Beginners)',
 'Non Directional Weekly Options Trading System - ETF & Emini',
 'The Complete Position Trading Course: Position Trading Stock',
 'Master Iron Condors - Double the credit for half the risk',
 'Basics of investing in Mutual Funds',
 'A Value Investing Approach to the Stock Market',
 'Learn how to INVEST for huge profits or make it big trading!',
 'How to Fund your Million Dollar Idea: Equity, Debt, Unfund',
 'Mastering Candlestick Charting : High Probability Trading',
 'Binary Options Course - Level 2',
 'Stock Technical Analysis with R',
 'Get to know the VIX Index (aka \'The Fear Index)"',
 'Apply finance concepts for smart project management',
 'Introduction to Futures Trading and Live Trade Demonstration',
 'Crowdfunding to Win',
 'Comprehensive Forex Mastery Program',
 'Preparation of Consolidated Financial Statements (Basic)',
 "Succeed in Bonds Even if You Don't Know Where to Start",
 'Learn to Trade for Profit: Ten Most Profitable Trading Rules',
 "Succeed in Lotto Even if You Don't Know Where to Start!",
 'CFA Corporate Finance Level 2',
 'Pin Bars: The Most Powerful Forex Trading Signal',
 'Stock Options Trades Using Interactive Brokers',
 'Introduction to Options - Strategies For Consistent Profits',
 'Risk in Forex Transactions - for CA / CS / CFA exams',
 'Basics of Business Statistics (College Level)',
 'Trading Seasonal Price Patterns in Stocks, Futures, & Forex!',
 'Interpreting Financial Statements',
 'Introduction to Bookkeeping (Accounting)',
 'CREDIT SPREAD SURGERY - Bear Call and Bull Put Mastery ',
 'Investment Banking: How to Land a Job on Wall Street',
 'Learn To Invest In Index Funds and ETFs In 7 Easy Steps',
 'Financial modeling: Build a multiples valuation model',
 'Trade Recap I - A Real Look at Futures Options Markets',
 'Advanced Stock Options for Serious Equity Investors!',
 'Trading Binary Options for Fun and Profit',
 'CFA: Fast Track your career in Finance',
 'How to be a Profitable Forex Trader',
 'Excel Dashboard - Interactive Excel Dashboard and Charts',
 'Accounting 101: Learn Business Finance Forecasting in 60mins',
 'The Securities Trade Lifecycle',
 'Double your Forex Account using the MAGIC MA trading robot',
 'Technical Analysis 101: How to Profit During Market Crashes',
 'Advanced Accounting for Investment Banking',
 'Investing In Stocks With 10 Simple Rules',
 'Venture Capital. What is it and Why it Matters to You!',
 'Cash Flow Valuation: Develop Your Financial Literacy',
 'Direction-Independ Trading - Elite Forex Traders  Strategy',
 'How to Become a Financial Analyst from Scratch!',
 'First Steps to Trading the Forexmarkets : Technical Analysis',
 'Financial analysis: Compare performance of companies',
 'Forex for Beginners: Easy Forex Trading for Beginners',
 'Investment Crowdfunding 101 (a.k.a Equity Crowdfunding)',
 'Read financial statements like a pro',
 '10 Numbers Every Business Owner Should Know',
 'Learn How To Trade Gold In 2017',
 'IAS 18 - Revenue',
 'Forex Trading: The High ROI Forex Trading End of Day Course',
 'Fundraise the Simplified Way: A Crowdfunding Blueprint',
 'Fundamentals of Accounting for Business Owners',
 'Practical Financial Statement Analysis',
 'Forex Management - Detailed Study for CA / CS / CFA Exams',
 'Financial Statement Review 101:  How to Find Errors',
 'Professional Risk Manager (PRM) Certification: Level 1',
 'International Tax  - Tax Beyond boundaries',
 'The Complete Financial Statement Analysis Course',
 'Advanced Excel functions',
 'Penny Stocks Value & Chart Pattern Trading (2 Course Bundle)',
 'Candlestick Analysis For Professional Traders',
 'Build A Career In Forex Trading- Learn Fundamental Analysis',
 'Financial Modeling: Build a Complete DCF Valuation Model',
 'Hands-on Financial Modeling (With 6 Excel Templates)',
 'CAIIB Advanced Bank Management (Part I)',
 'Stock Market investment:Non financial fundamental analysis',
 'Learn How to Play CashFlow Game',
 'Basics of Business Finance',
 'Accounting Made Easy 2',
 'Bitcoin: el futuro del dinero, hoy',
 'Aprende a invertir practicando',
 'Trading con retrocesos de Fibonacci',
 'Mit Finanzwissen zu besserem Unternehmertum',
 'Como hacer empresa en 10 sesiones prácticas',
 'المحاسبة للإداريين و غير المحاسبين',
 '株式投資で本当のファンダメンタル分析ができるようになる',
 'Curso de Trading práctico basado en casos reales',
 'Curso Avanzado de Trading',
 'สอนเทรดไบนารี่ อ๊อฟชั่นอย่างง่าย',
 'MQL4 Tutorial Golden Goose',
 'Análise de Concessão de Crédito',
 'Technical Analysis Using Elliott Wave Theory',
 'The Basics Of Volume Analysis',
 'Crash Course on Cost of Capital and Capital Structuring',
 'Business Accounting Made Easy',
 'Build a DCF Model from Scratch',
 'Multiply your returns using \'Value Investing",https://www.udemy.com/multiply-your-returns-using-value-investing/,true,20,1942,19,63,All Levels,4.5 hours,2015-07-23T00:08:33Z\n874284,Weekly Forex Analysis by Baraq FX"',
 'Technical Analysis - A practical approach for trade entry',
 'Mastering Technical Analysis : Maximizing Trading Profits',
 'The Complete Guide to Professional Trading with Elliott Wave',
 'A Complete Guide to Becoming a Trader on the Forex Market',
 'Stock Market for Beginners - Complete Starter Toolkit',
 'Beginners Binary Options Course',
 'Technical Analysis 101: Secrets of Trading Revealed',
 "Forex: What's a Trend and When it is Strong and Reliable",
 'Volatility Trading Analysis with R',
 'How To Profit From Stock Market Volatility',
 'Awaken the Accountant in You | Master the Accounting Basics',
 'WE WILL PAY YOU TO TRADE WITH US',
 'Situational Trading: Proven Option Strategy for any Scenario',
 'Portfolio Management for CA / CS / CFA exams',
 'Algorithmic Trading in MATLAB: WFAToolbox App GUI (Finance)',
 'Finding an Unlimited Amount of Investors',
 'Bookkeeping Made Easy',
 'BITCOIN VISUALLY. Part I.',
 'Learn and Master the Basics of Finance',
 'FOREX : LearnTo Trade the Improved ( Advanced ) Patterns',
 'Mastering the Market : (Technical Analysis + Candlestick)',
 'Mastering Countertrend Trading : High Profit Trading Pattern',
 'Exam 1 Review - Managerial Accounting (U of H)',
 '* An Integrated Approach to the Fundamentals of Accounting',
 'Get to grips with the CFA calculator',
 'Financial Model Fundamentals-Learn the Essential Skills',
 'Forex: Economic News Trading',
 'Analyze Real Estate Investments | Financial Modeling',
 'Forex For Beginners - A Guide To Currency Trading',
 'Raise Your Credit Score to 800 Or More....',
 'Financial Management Budgeting Techniques',
 'Forex Killing Divergence - How to trade with precision',
 'Working Capital Management for CA / CFA / CPA Exams',
 'Risk Analysis - Capital Budgeting for CA / CS / CFA exams',
 'Corporate Finance 101: Financial Statement Analysis & Ratios',
 'Mastering Futures Options for Beginners - Your Top 5 Plays!',
 'Professional Options Trading, Simplified',
 'Advanced Options Concepts - Probability, Greeks, Simulation',
 'Accounting Basics - A Complete Study',
 'Case Studies in Macro Economics',
 'My Forex Strategy that win consistently over and over',
 'Understand Banks & Financial Markets ',
 'Stock Technical Analysis with Python',
 'How to Become an Accountant from scratch!',
 'How to invest in Gold',
 'Automate Your Finances',
 'MBA Accounting and Finance for Managers(Paper MS04 of IGNOU)',
 'Accounting Made Easy: A Quick Guide to Financial Accounting',
 'Futures/Commodity Training (Basics)',
 'Cost Accounting Marginal Costing Theory and Practice',
 'The Big Volatility Short: The Best Trade On Wall Street!',
 'Master Finance in Three Hours',
 'Learn Options on Futures for Hedging Options and Stocks',
 'Option selling trading as income source. Beginners friendly',
 'Introduction to Value Growth Investing',
 'Become A Forex Trader - Forex trading like a professional',
 'Hedge Fund Trading System',
 'Bulletproof Personal Finance: Expert Asset Allocation',
 'Financial Accounting: The Complete Introductory Crash Course',
 'Learn About Trading Options from a real wallstreet trader',
 'Forex Rate -Why it fluctuates -for CA / CMA / CS / CFA Exams',
 'How to Build a Massive Stock Portfolio from Zero!',
 'Introductory Forex Trading Course',
 'Budgeting Hacks to Build Wealth!',
 'Accounting and Finance for Bankers - A Comprehensive Study',
 'Forex Prep Academy for Beginners-Real trades!',
 'Accounting for Deferred Taxes (Professional Course Level)',
 'TRADING TRUTHS',
 'The Binary Institute - Introductory Course in Binary Options',
 'Forex Trading vs Option Trading',
 'How to Invest in Stocks + Billionaire Investing Tips',
 'Value Investing For Beginners',
 'TRADING TACTICS',
 'MQL4 Tutorial Bootcamp - Trading Robot Coding in Metatrader4',
 'Ultimate Retirement: Build Your Own Dynamic Retirement Plan',
 'build a solid foundation for trading options',
 'Forex Scam: Avoid the scam today',
 'Cost Accounting Crash Course',
 'Option Trading for Rookies: Basic Option Strategies',
 'Business Analysis:  Working with Use Cases',
 'Learn to Raise the Funds You Need via Crowdfunding',
 'Business finances',